# ----------------------------------------------------- 
# Environment Variables
# name: "Default"
# ----------------------------------------------------- 

# Default Settings in ml4w.conf

# Pavucontrol floating
windowrule {
  name = pulseaudio-pavucontrol
  match:class = (.*org.pulseaudio.pavucontrol.*)
  size = {700, 600}
  float = true
  center = true
  pin = true
}

# Waypaper
windowrule {
  name = waypaper
  match:class = (.*waypaper.*)
  size = {900, 700}
  float = true
  center = true
  pin = true
}

# System Mission Center
windowrule {
  name = mission-center
  match:class = (io.missioncenter.MissionCenter)
  size = {900, 600}
  float = true
  center = true
  pin = true
}

windowrule {
  name = mission-center-prefs
  match:class = (missioncenter)
  match:title = ^(Preferences)$
  float = true
  center = true
  pin = true
}

# Gnome Calculator
windowrule {
  name = gnome-calc
  match:class = (org.gnome.Calculator)
  size = {700, 600}
  float = true
  center = true
}

# Emoji Picker
windowrule {
  name = emoji-picker
  match:class = (it.mijorus.smile)
  move = "100%-w-40 90"
  float = true
  pin = true
}

# Hyprland Share Picker
windowrule {
  name = hyprland-share-picker
  match:class = (hyprland-share-picker)
  size = {600, 400}
  float = true
  center = true
  pin = true
}

# General floating
windowrule {
  name = dotfiles-floating
  match:class = (dotfiles-floating)
  size = {1000, 700}
  float = true
  center = true
  pin = true
}

# XDG Desktop Portal
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# QT
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1

# GDK
env = GDK_SCALE,1

# Toolkit Backend
env = GDK_BACKEND,wayland,x11,*
env = CLUTTER_BACKEND,wayland

# Mozilla
env = MOZ_ENABLE_WAYLAND,1

# Set the cursor size for xcursor
env = XCURSOR_SIZE,24

# Disable appimage launcher by default
env = APPIMAGELAUNCHER_DISABLE,1

# Ozone
env = OZONE_PLATFORM,wayland
env = ELECTRON_OZONE_PLATFORM_HINT,wayland

# Python
env = PYTHONPATH,/usr/lib/python3.12/site-packages:/usr/lib/python3.13/site-packages
