set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Better Git integration within vim
Plugin 'tpope/vim-fugitive'

" Molokai color scheme
Plugin 'tomasr/molokai'

" Pywal color scheme generation
Plugin 'dylanaraps/wal.vim'

call vundle#end()

"colorscheme wal
colorscheme molokai
let g:molokai_original=1

syntax on
set number
set relativenumber

" Set indent settings
filetype plugin indent on
" Show existing tab with 4 spaces
set tabstop=4
" When indenting with '>', use 4 spaces
set shiftwidth=4
" On pressing 'Tab', insert 4 spaces
set expandtab

map <F6> :setlocal spell! spelllang=en_gb<CR>
