automobilemenu = {
  { "asc2log",             "urxvt -e sh -c 'asc2log ; bash'" },
  { "bcmserver",           "urxvt -e sh -c 'bcmserver ; bash'" },
  { "can-calc-bit-timing", "urxvt -e sh -c 'can-calc-bit-timing ; bash'" },
  { "canbusload",          "urxvt -e sh -c 'canbusload ; bash'" },
  { "candump",             "urxvt -e sh -c 'candump ; bash'" },
  { "canfdtest",           "urxvt -e sh -c 'canfdtest ; bash'" },
  { "cangen",              "urxvt -e sh -c 'cangen ; bash'" },
  { "cangw",               "urxvt -e sh -c 'cangw ; bash'" },
  { "canlogserver",        "urxvt -e sh -c 'canlogserver ; bash'" },
  { "cansend",             "urxvt -e sh -c 'cansend ; bash'" },
  { "cansequence",         "urxvt -e sh -c 'cansequence ; bash'" },
  { "cansniffer",          "urxvt -e sh -c 'cansniffer ; bash'" },
  { "isotpdump",           "urxvt -e sh -c 'isotpdump ; bash'" },
  { "isotpperf",           "urxvt -e sh -c 'isotpperf ; bash'" },
  { "isotprecv",           "urxvt -e sh -c 'isotprecv ; bash'" },
  { "isotptun",            "urxvt -e sh -c 'isotptun ; bash'" },
  { "j1939acd",            "urxvt -e sh -c 'j1939acd ; bash'" },
  { "j1939cat",            "urxvt -e sh -c 'j1939cat ; bash'" },
  { "j1939sr",             "urxvt -e sh -c 'j1939sr ; bash'" },
  { "log2asc",             "urxvt -e sh -c 'log2asc ; bash'" },
  { "log2long",            "urxvt -e sh -c 'log2long ; bash'" },
  { "mcp251xfd-dump",      "urxvt -e sh -c 'mcp251xfd-dump ; bash'" },
  { "slcan_attach",        "urxvt -e sh -c 'slcan_attach ; bash'" },
  { "slcand",              "urxvt -e sh -c 'slcand ; bash'" },
  { "slcanpty",            "urxvt -e sh -c 'slcanpty ; bash'" },
  { "testj1939",           "urxvt -e sh -c 'testj1939 ; bash'" },
  { "canalyzat0r",         "urxvt -e sh -c 'canalyzat0r ; bash'" },
  { "cantoolz",            "urxvt -e sh -c 'cantoolz -h ; bash'" },
  { "udsim",               "urxvt -e sh -c 'udsim -h ; bash'" },
}

return automobilemenu
