automationmenu = {
  { "airgeddon",               "urxvt -e sh -c 'airgeddon ; bash'" },
  { "apt2",                    "urxvt -e sh -c 'apt2 -h ; bash'" },
  { "armitage",                "urxvt -e sh -c 'armitage -h ; bash'" },
  { "teamserver",              "urxvt -e sh -c 'teamserver ; bash'" },
  { "armscgen",                "urxvt -e sh -c 'armscgen -h ; bash'" },
  { "atscan",                  "urxvt -e sh -c 'atscan ; bash'" },
  { "automato",                "urxvt -e sh -c 'automato ; bash'" },
  { "autonessus",              "urxvt -e sh -c 'autonessus -h ; bash'" },
  { "autonse",                 "urxvt -e sh -c 'autonse ; bash'" },
  { "autopwn",                 "urxvt -e sh -c 'autopwn -h ; bash'" },
  { "autopwn-cli",             "urxvt -e sh -c 'autopwn-cli ; bash'" },
  { "autorecon",               "urxvt -e sh -c 'autorecon -h ; bash'" },
  { "autovpn",                 "urxvt -e sh -c 'autovpn ; bash'" },
  { "avet",                    "urxvt -e sh -c 'avet ; bash'" },
  { "awsbucketdump",           "urxvt -e sh -c 'awsbucketdump -h ; bash'" },
  { "backdoorme",              "urxvt -e sh -c 'backdoorme ; bash'" },
  { "barq",                    "urxvt -e sh -c 'barq -h ; bash'" },
  { "binex",                   "urxvt -e sh -c 'binex -h ; bash'" },
  { "blueranger",              "urxvt -e sh -c 'blueranger ; bash'" },
  { "brutespray",              "urxvt -e sh -c 'brutespray -h ; bash'" },
  { "brutex",                  "urxvt -e sh -c 'brutex ; bash'" },
  { "brutex-masscan",          "urxvt -e sh -c 'brutex-masscan ; bash'" },
  { "byepass",                 "urxvt -e sh -c 'byepass -h ; bash'" },
  { "passtime",                "urxvt -e sh -c 'passtime -h ; bash'" },
  { "cewl",                    "urxvt -e sh -c 'cewl -h ; bash'" },
  { "cewl-fab",                "urxvt -e sh -c 'cewl-fab ; bash'" },
  { "checksec",                "urxvt -e sh -c 'checksec --help ; bash'" },
  { "cisco-snmp-enumeration",  "urxvt -e sh -c 'cisco-snmp-enumeration ; bash'" },
  { "acorn",                   "urxvt -e sh -c 'acorn ; bash'" },
  { "zuul-es5.yml",            "urxvt -e sh -c 'zuul-es5.yml ; bash'" },
  { "zuul-es6.yml",            "urxvt -e sh -c 'zuul-es6.yml ; bash'" },
  { "uuid",                    "urxvt -e sh -c 'uuid ; bash'" },
  { "he",                      "urxvt -e sh -c 'he ; bash'" },
  { "jsesc",                   "urxvt -e sh -c 'jsesc ; bash'" },
  { "_mocha",                  "urxvt -e sh -c '_mocha ; bash'" },
  { "mocha",                   "urxvt -e sh -c 'mocha ; bash'" },
  { "semver",                  "urxvt -e sh -c 'semver ; bash'" },
  { "uuid",                    "urxvt -e sh -c 'uuid ; bash'" },
  { "which",                   "urxvt -e sh -c 'which ; bash'" },
  { "clusterd",                "urxvt -e sh -c 'clusterd -h ; bash'" },
  { "cmsmap",                  "urxvt -e sh -c 'cmsmap -h ; bash'" },
  { "codeql",                  "urxvt -e sh -c 'codeql ; bash'" },
  { "java",                    "urxvt -e sh -c 'java ; bash'" },
  { "javac",                   "urxvt -e sh -c 'javac ; bash'" },
  { "keytool",                 "urxvt -e sh -c 'keytool ; bash'" },
  { "rmid",                    "urxvt -e sh -c 'rmid ; bash'" },
  { "rmiregistry",             "urxvt -e sh -c 'rmiregistry ; bash'" },
  { "serialver",               "urxvt -e sh -c 'serialver ; bash'" },
  { "tsc",                     "urxvt -e sh -c 'tsc ; bash'" },
  { "tsserver",                "urxvt -e sh -c 'tsserver ; bash'" },
  { "java",                    "urxvt -e sh -c 'java ; bash'" },
  { "javac",                   "urxvt -e sh -c 'javac ; bash'" },
  { "keytool",                 "urxvt -e sh -c 'keytool ; bash'" },
  { "rmid",                    "urxvt -e sh -c 'rmid ; bash'" },
  { "rmiregistry",             "urxvt -e sh -c 'rmiregistry ; bash'" },
  { "serialver",               "urxvt -e sh -c 'serialver ; bash'" },
  { "commix",                  "urxvt -e sh -c 'commix ; bash'" },
  { "commonspeak",             "urxvt -e sh -c 'commonspeak -h ; bash'" },
  { "cook",                    "urxvt -e sh -c 'cook -h ; bash'" },
  { "crunch",                  "urxvt -e sh -c 'crunch -h ; bash'" },
  { "darkspiritz",             "urxvt -e sh -c 'darkspiritz -h ; bash'" },
  { "deathstar",               "urxvt -e sh -c 'deathstar -h ; bash'" },
  { "domained",                "urxvt -e sh -c 'domained -h ; bash'" },
  { "dorknet",                 "urxvt -e sh -c 'dorknet -h ; bash'" },
  { "dracnmap",                "urxvt -e sh -c 'dracnmap ; bash'" },
  { "dracnmap-drac0s",         "urxvt -e sh -c 'dracnmap-drac0s ; bash'" },
  { "dumb0",                   "urxvt -e sh -c 'dumb0 -h ; bash'" },
  { "easy-creds",              "urxvt -e sh -c 'easy-creds ; bash'" },
  { "easyda",                  "urxvt -e sh -c 'easyda ; bash'" },
  { "empire",                  "urxvt -e sh -c 'empire -h ; bash'" },
  { "faraday-manage",          "urxvt -e sh -c 'faraday-manage ; bash'" },
  { "faraday-searcher",        "urxvt -e sh -c 'faraday-searcher ; bash'" },
  { "faraday-server",          "urxvt -e sh -c 'faraday-server ; bash'" },
  { "firstorder",              "urxvt -e sh -c 'firstorder -h ; bash'" },
  { "fstealer",                "urxvt -e sh -c 'fstealer -h ; bash'" },
  { "gitdump",                 "urxvt -e sh -c 'gitdump ; bash'" },
  { "githubcloner",            "urxvt -e sh -c 'githubcloner -h ; bash'" },
  { "glue",                    "urxvt -e sh -c 'glue -h ; bash'" },
  { "goohak",                  "urxvt -e sh -c 'goohak ; bash'" },
  { "gooscan",                 "urxvt -e sh -c 'gooscan -h ; bash'" },
  { "harpoon",                 "urxvt -e sh -c 'harpoon -h ; bash'" },
  { "hate-crack",              "urxvt -e sh -c 'hate-crack ; bash'" },
  { "iloscan",                 "urxvt -e sh -c 'iloscan ; bash'" },
  { "intersect-create",        "urxvt -e sh -c 'intersect-create ; bash'" },
  { "inurlbr",                 "urxvt -e sh -c 'inurlbr -h ; bash'" },
  { "ipmipwn",                 "urxvt -e sh -c 'ipmipwn ; bash'" },
  { "jaidam",                  "urxvt -e sh -c 'jaidam ; bash'" },
  { "unix-jboss-autopwn",      "urxvt -e sh -c 'unix-jboss-autopwn ; bash'" },
  { "win-jboss-autopwn",       "urxvt -e sh -c 'win-jboss-autopwn ; bash'" },
  { "kernelpop",               "urxvt -e sh -c 'kernelpop -h ; bash'" },
  { "killcast",                "urxvt -e sh -c 'killcast -h ; bash'" },
  { "koadic",                  "urxvt -e sh -c 'koadic ; bash'" },
  { "dynwrapx.manifest",       "urxvt -e sh -c 'dynwrapx.manifest ; bash'" },
  { "lazydroid",               "urxvt -e sh -c 'lazydroid ; bash'" },
  { "ldapaddgroup",            "urxvt -e sh -c 'ldapaddgroup -h ; bash'" },
  { "ldapaddmachine",          "urxvt -e sh -c 'ldapaddmachine -h ; bash'" },
  { "ldapadduser",             "urxvt -e sh -c 'ldapadduser -h ; bash'" },
  { "ldapaddusertogroup",      "urxvt -e sh -c 'ldapaddusertogroup -h ; bash'" },
  { "ldapdeletegroup",         "urxvt -e sh -c 'ldapdeletegroup -h ; bash'" },
  { "ldapdeletemachine",       "urxvt -e sh -c 'ldapdeletemachine -h ; bash'" },
  { "ldapdeleteuser",          "urxvt -e sh -c 'ldapdeleteuser -h ; bash'" },
  { "ldapdeleteuserfromgroup", "urxvt -e sh -c 'ldapdeleteuserfromgroup -h ; bash'" },
  { "ldapfinger",              "urxvt -e sh -c 'ldapfinger -h ; bash'" },
  { "ldapgid",                 "urxvt -e sh -c 'ldapgid -h ; bash'" },
  { "ldapid",                  "urxvt -e sh -c 'ldapid -h ; bash'" },
  { "ldapinit",                "urxvt -e sh -c 'ldapinit -h ; bash'" },
  { "ldapmodifygroup",         "urxvt -e sh -c 'ldapmodifygroup -h ; bash'" },
  { "ldapmodifymachine",       "urxvt -e sh -c 'ldapmodifymachine -h ; bash'" },
  { "ldapmodifyuser",          "urxvt -e sh -c 'ldapmodifyuser -h ; bash'" },
  { "ldaprenamegroup",         "urxvt -e sh -c 'ldaprenamegroup -h ; bash'" },
  { "ldaprenamemachine",       "urxvt -e sh -c 'ldaprenamemachine -h ; bash'" },
  { "ldaprenameuser",          "urxvt -e sh -c 'ldaprenameuser -h ; bash'" },
  { "lsldap",                  "urxvt -e sh -c 'lsldap -h ; bash'" },
  { "legion",                  "urxvt -e sh -c 'legion -h ; bash'" },
  { "linikatz",                "urxvt -e sh -c 'linikatz ; bash'" },
  { "linset",                  "urxvt -e sh -c 'linset ; bash'" },
  { "lyricpass",               "urxvt -e sh -c 'lyricpass -h ; bash'" },
  { "maskprocessor",           "urxvt -e sh -c 'maskprocessor -h ; bash'" },
  { "massbleed",               "urxvt -e sh -c 'massbleed ; bash'" },
  { "masscan-automation",      "urxvt -e sh -c 'masscan-automation -h ; bash'" },
  { "massexpconsole",          "urxvt -e sh -c 'massexpconsole ; bash'" },
  { "mentalist",               "urxvt -e sh -c 'mentalist ; bash'" },
  { "merlin-server",           "urxvt -e sh -c 'merlin-server -h ; bash'" },
  { "mitmap-old",              "urxvt -e sh -c 'mitmap-old -h ; bash'" },
  { "morpheus",                "urxvt -e sh -c 'morpheus ; bash'" },
  { "etter.dns",               "urxvt -e sh -c 'etter.dns ; bash'" },
  { "http.lua",                "urxvt -e sh -c 'http.lua ; bash'" },
  { "warn.ogg",                "urxvt -e sh -c 'warn.ogg ; bash'" },
  { "msf-mpc",                 "urxvt -e sh -c 'msf-mpc -h ; bash'" },
  { "msfenum",                 "urxvt -e sh -c 'msfenum -h ; bash'" },
  { "multiscanner",            "urxvt -e sh -c 'multiscanner -h ; bash'" },
  { "multiscanner-api",        "urxvt -e sh -c 'multiscanner-api ; bash'" },
  { "multiscanner-web",        "urxvt -e sh -c 'multiscanner-web ; bash'" },
  { "mutator",                 "urxvt -e sh -c 'mutator -h ; bash'" },
  { "nettacker",               "urxvt -e sh -c 'nettacker -h ; bash'" },
  { "nosqlattack",             "urxvt -e sh -c 'nosqlattack ; bash'" },
  { "nullscan",                "urxvt -e sh -c 'nullscan -H ; bash'" },
  { "autotailor",              "urxvt -e sh -c 'autotailor ; bash'" },
  { "oscap",                   "urxvt -e sh -c 'oscap -h ; bash'" },
  { "oscap-chroot",            "urxvt -e sh -c 'oscap-chroot -h ; bash'" },
  { "oscap-docker",            "urxvt -e sh -c 'oscap-docker -h ; bash'" },
  { "oscap-podman",            "urxvt -e sh -c 'oscap-podman -h ; bash'" },
  { "oscap-run-sce-script",    "urxvt -e sh -c 'oscap-run-sce-script ; bash'" },
  { "oscap-vm",                "urxvt -e sh -c 'oscap-vm -h ; bash'" },
  { "scap-as-rpm",             "urxvt -e sh -c 'scap-as-rpm -h ; bash'" },
  { "osslsigncode",            "urxvt -e sh -c 'osslsigncode -h ; bash'" },
  { "owtf",                    "urxvt -e sh -c 'owtf ; bash'" },
  { "panoptic",                "urxvt -e sh -c 'panoptic -h ; bash'" },
  { "pastejacker",             "urxvt -e sh -c 'pastejacker ; bash'" },
  { "pasv-agrsv",              "urxvt -e sh -c 'pasv-agrsv -h ; bash'" },
  { "penbox",                  "urxvt -e sh -c 'penbox ; bash'" },
  { "pentestly",               "urxvt -e sh -c 'pentestly -h ; bash'" },
  { "pentmenu",                "urxvt -e sh -c 'pentmenu ; bash'" },
  { "phemail",                 "urxvt -e sh -c 'phemail -h ; bash'" },
  { "pin",                     "urxvt -e sh -c 'pin ; bash'" },
  { "pindb",                   "urxvt -e sh -c 'pindb ; bash'" },
  { "pindb.sig",               "urxvt -e sh -c 'pindb.sig ; bash'" },
  { "pindb",                   "urxvt -e sh -c 'pindb ; bash'" },
  { "pindb.sig",               "urxvt -e sh -c 'pindb.sig ; bash'" },
  { "pmcma",                   "urxvt -e sh -c 'pmcma ; bash'" },
  { "portia",                  "urxvt -e sh -c 'portia ; bash'" },
  { "ptf",                     "urxvt -e sh -c 'ptf ; bash'" },
  { "pureblood",               "urxvt -e sh -c 'pureblood ; bash'" },
  { "pwndrop",                 "urxvt -e sh -c 'pwndrop -h ; bash'" },
  { "pyfuscation",             "urxvt -e sh -c 'pyfuscation -h ; bash'" },
  { "arsenic-check-ie11",      "urxvt -e sh -c 'arsenic-check-ie11 ; bash'" },
  { "shodan",                  "urxvt -e sh -c 'shodan ; bash'" },
  { "shodan2",                 "urxvt -e sh -c 'shodan2 ; bash'" },
  { "recomposer",              "urxvt -e sh -c 'recomposer -h ; bash'" },
  { "rhodiola",                "urxvt -e sh -c 'rhodiola -h ; bash'" },
  { "rsmangler",               "urxvt -e sh -c 'rsmangler -h ; bash'" },
  { "sakis3g",                 "urxvt -e sh -c 'sakis3g --help ; bash'" },
  { "sandmap",                 "urxvt -e sh -c 'sandmap --help ; bash'" },
  { "sc-make",                 "urxvt -e sh -c 'sc-make ; bash'" },
  { "scap-workbench",          "urxvt -e sh -c 'scap-workbench ; bash'" },
  { "search1337",              "urxvt -e sh -c 'search1337 ; bash'" },
  { "sharesniffer",            "urxvt -e sh -c 'sharesniffer -h ; bash'" },
  { "shellerator",             "urxvt -e sh -c 'shellerator -h ; bash'" },
  { "shellme",                 "urxvt -e sh -c 'shellme -h ; bash'" },
  { "shellpop",                "urxvt -e sh -c 'shellpop -h ; bash'" },
  { "sign",                    "urxvt -e sh -c 'sign ; bash'" },
  { "sipvicious-svcrack",      "urxvt -e sh -c 'sipvicious-svcrack -h ; bash'" },
  { "sipvicious-svmap",        "urxvt -e sh -c 'sipvicious-svmap -h ; bash'" },
  { "sipvicious-svreport",     "urxvt -e sh -c 'sipvicious-svreport -h ; bash'" },
  { "sipvicious-svwar",        "urxvt -e sh -c 'sipvicious-svwar -h ; bash'" },
  { "sn00p",                   "urxvt -e sh -c 'sn00p ; bash'" },
  { "sn1per",                  "urxvt -e sh -c 'sn1per ; bash'" },
  { "http-default-accounts-fingerprints-nndefaccts.lua",
    "urxvt -e sh -c 'http-default-accounts-fingerprints-nndefaccts.lua ; bash'" },
  { "inurlbr.php",        "urxvt -e sh -c 'inurlbr.php ; bash'" },
  { "nmap-bootstrap.xsl", "urxvt -e sh -c 'nmap-bootstrap.xsl ; bash'" },
  { "spookflare",         "urxvt -e sh -c 'spookflare ; bash'" },
  { "ssl-phuck3r",        "urxvt -e sh -c 'ssl-phuck3r -h ; bash'" },
  { "statsprocessor",     "urxvt -e sh -c 'statsprocessor --help ; bash'" },
  { "thefatrat",          "urxvt -e sh -c 'thefatrat cd /usr/share/thefatrat ; ls ; bash'" },
  { "tiger",              "urxvt -e sh -c 'tiger -h ; bash'" },
  { "tlssled",            "urxvt -e sh -c 'tlssled -h ; bash'" },
  { "torctl",             "urxvt -e sh -c 'torctl ; bash'" },
  { "traxss",             "urxvt -e sh -c 'traxss -h ; bash'" },
  { "ttpassgen",          "urxvt -e sh -c 'ttpassgen -h ; bash'" },
  { "unix-privsc-check",  "urxvt -e sh -c 'unix-privsc-check ; bash'" },
  { "username-anarchy",   "urxvt -e sh -c 'username-anarchy -h ; bash'" },
  { "usernamer",          "urxvt -e sh -c 'usernamer -h ; bash'" },
  { "valhalla-cli",       "urxvt -e sh -c 'valhalla-cli -h ; bash'" },
  { "vbsmin",             "urxvt -e sh -c 'vbsmin -h ; bash'" },
  { "veil",               "urxvt -e sh -c 'veil ; bash'" },
  { "vlan-hopping",       "urxvt -e sh -c 'vlan-hopping ; bash'" },
  { "voiphopper",         "urxvt -e sh -c 'voiphopper -h ; bash'" },
  { "wifi-autopwner",     "urxvt -e sh -c 'wifi-autopwner -h ; bash'" },
  { "wikigen",            "urxvt -e sh -c 'wikigen ; bash'" },
  { "wnmap",              "urxvt -e sh -c 'wnmap -h ; bash'" },
  { "xcat",               "urxvt -e sh -c 'xcat ; bash'" },
  { "yinjector",          "urxvt -e sh -c 'yinjector -h ; bash'" },
  { "zeratool",           "urxvt -e sh -c 'zeratool -h ; bash'" },
  { "zirikatu",           "urxvt -e sh -c 'zirikatu ; bash'" },
}

return automationmenu
