backdoormenu = {
  { "arcane",                   "urxvt -e sh -c 'arcane -h ; bash'" },
  { "avet",                     "urxvt -e sh -c 'avet ; bash'" },
  { "backcookie",               "urxvt -e sh -c 'backcookie -h ; bash'" },
  { "backdoor-factory",         "urxvt -e sh -c 'backdoor-factory -h ; bash'" },
  { "backdoorme",               "urxvt -e sh -c 'backdoorme ; bash'" },
  { "backdoorppt",              "urxvt -e sh -c 'backdoorppt ; bash'" },
  { "barq",                     "urxvt -e sh -c 'barq -h ; bash'" },
  { "cymothoa-udp_server",      "urxvt -e sh -c 'cymothoa-udp_server ; bash'" },
  { "demiguise",                "urxvt -e sh -c 'demiguise -h ; bash'" },
  { "donut",                    "urxvt -e sh -c 'donut -h ; bash'" },
  { "dr0p1t",                   "urxvt -e sh -c 'dr0p1t -h ; bash'" },
  { "evil-winrm",               "urxvt -e sh -c 'evil-winrm -h ; bash'" },
  { "evilpdf",                  "urxvt -e sh -c 'evilpdf -h ; bash'" },
  { "exe2image",                "urxvt -e sh -c 'exe2image ; bash'" },
  { "gobd",                     "urxvt -e sh -c 'gobd -h ; bash'" },
  { "harness",                  "urxvt -e sh -c 'harness ; bash'" },
  { "hercules-payload",         "urxvt -e sh -c 'hercules-payload ; bash'" },
  { "hotpatcher",               "urxvt -e sh -c 'hotpatcher -h ; bash'" },
  { "iloscan",                  "urxvt -e sh -c 'iloscan ; bash'" },
  { "k55",                      "urxvt -e sh -c 'k55 -h ; bash'" },
  { "kimi",                     "urxvt -e sh -c 'kimi -h ; bash'" },
  { "kwetza",                   "urxvt -e sh -c 'kwetza --help ; bash'" },
  { "interpatch",               "urxvt -e sh -c 'interpatch -h ; bash'" },
  { "lfi-image-helper",         "urxvt -e sh -c 'lfi-image-helper ; bash'" },
  { "linux-inject",             "urxvt -e sh -c 'linux-inject -h ; bash'" },
  { "linux-inject-32",          "urxvt -e sh -c 'linux-inject-32 -h ; bash'" },
  { "ms-sys",                   "urxvt -e sh -c 'ms-sys -h ; bash'" },
  { "msf-mpc",                  "urxvt -e sh -c 'msf-mpc -h ; bash'" },
  { "msvpwn",                   "urxvt -e sh -c 'msvpwn -h ; bash'" },
  { "nxcrypt",                  "urxvt -e sh -c 'nxcrypt -h ; bash'" },
  { "patchkit",                 "urxvt -e sh -c 'patchkit -h ; bash'" },
  { "pivotsuite",               "urxvt -e sh -c 'pivotsuite -h ; bash'" },
  { "pixload-bmp",              "urxvt -e sh -c 'pixload-bmp ; bash'" },
  { "pixload-gif",              "urxvt -e sh -c 'pixload-gif ; bash'" },
  { "pixload-jpg",              "urxvt -e sh -c 'pixload-jpg ; bash'" },
  { "powerstager",              "urxvt -e sh -c 'powerstager -h ; bash'" },
  { "pwncat",                   "urxvt -e sh -c 'pwncat cd /usr/share/windows/pwncat ; ls ; bash'" },
  { "pyrasite",                 "urxvt -e sh -c 'pyrasite -h ; bash'" },
  { "pyrasite-memory-viewer",   "urxvt -e sh -c 'pyrasite-memory-viewer ; bash'" },
  { "remot3d",                  "urxvt -e sh -c 'remot3d ; bash'" },
  { "rrs",                      "urxvt -e sh -c 'rrs -h ; bash'" },
  { "rspet-client",             "urxvt -e sh -c 'rspet-client ; bash'" },
  { "rspet-server",             "urxvt -e sh -c 'rspet-server ; bash'" },
  { "saruman",                  "urxvt -e sh -c 'saruman ; bash'" },
  { "sb0x",                     "urxvt -e sh -c 'sb0x -h ; bash'" },
  { "shellinaboxd",             "urxvt -e sh -c 'shellinaboxd -h ; bash'" },
  { "shellter",                 "urxvt -e sh -c 'shellter ; bash'" },
  { "sherlocked",               "urxvt -e sh -c 'sherlocked ; bash'" },
  { "stripx",                   "urxvt -e sh -c 'stripx ; bash'" },
  { "stub",                     "urxvt -e sh -c 'stub ; bash'" },
  { "shootback-master",         "urxvt -e sh -c 'shootback-master -h ; bash'" },
  { "shootback-slaver",         "urxvt -e sh -c 'shootback-slaver -h ; bash'" },
  { "silenttrinity",            "urxvt -e sh -c 'silenttrinity -h ; bash'" },
  { "silenttrinity-teamserver", "urxvt -e sh -c 'silenttrinity-teamserver -h ; bash'" },
  { "trixd00r",                 "urxvt -e sh -c 'trixd00r -H ; bash'" },
  { "u3-pwn",                   "urxvt -e sh -c 'u3-pwn ; bash'" },
  { "webacoo",                  "urxvt -e sh -c 'webacoo -h ; bash'" },
  { "webspa",                   "urxvt -e sh -c 'webspa -help ; bash'" },
  { "weevely",                  "urxvt -e sh -c 'weevely -h ; bash'" },
}

return backdoormenu
