binarymenu = {
  { "amber",                    "urxvt -e sh -c 'amber ; bash'" },
  { "amoco",                    "urxvt -e sh -c 'amoco ; bash'" },
  { "androarsc",                "urxvt -e sh -c 'androarsc ; bash'" },
  { "androcg",                  "urxvt -e sh -c 'androcg ; bash'" },
  { "androdd",                  "urxvt -e sh -c 'androdd ; bash'" },
  { "androdis",                 "urxvt -e sh -c 'androdis ; bash'" },
  { "androguard",               "urxvt -e sh -c 'androguard -h ; bash'" },
  { "androgui",                 "urxvt -e sh -c 'androgui ; bash'" },
  { "androlyze",                "urxvt -e sh -c 'androlyze ; bash'" },
  { "androsign",                "urxvt -e sh -c 'androsign ; bash'" },
  { "angr-management",          "urxvt -e sh -c 'angr-management ; bash'" },
  { "avet",                     "urxvt -e sh -c 'avet ; bash'" },
  { "backdoor-factory",         "urxvt -e sh -c 'backdoor-factory -h ; bash'" },
  { "bagbak",                   "urxvt -e sh -c 'bagbak -h ; bash'" },
  { "BARFcfg",                  "urxvt -e sh -c 'BARFcfg -h ; bash'" },
  { "BARFcg",                   "urxvt -e sh -c 'BARFcg -h ; bash'" },
  { "BARFgadgets",              "urxvt -e sh -c 'BARFgadgets -h ; bash'" },
  { "bdfproxy",                 "urxvt -e sh -c 'bdfproxy -h ; bash'" },
  { "bgrep",                    "urxvt -e sh -c 'bgrep ; bash'" },
  { "binaryninja-demo",         "urxvt -e sh -c 'binaryninja-demo ; bash'" },
  { "bindead",                  "urxvt -e sh -c 'bindead ; bash'" },
  { "bindiff",                  "urxvt -e sh -c 'bindiff ; bash'" },
  { "binexport2dump",           "urxvt -e sh -c 'binexport2dump ; bash'" },
  { "binflow",                  "urxvt -e sh -c 'binflow ; bash'" },
  { "binnavi",                  "urxvt -e sh -c 'binnavi ; bash'" },
  { "binwalk",                  "urxvt -e sh -c 'binwalk ; bash'" },
  { "binwally",                 "urxvt -e sh -c 'binwally -h ; bash'" },
  { "bsdiff",                   "urxvt -e sh -c 'bsdiff ; bash'" },
  { "bspatch",                  "urxvt -e sh -c 'bspatch ; bash'" },
  { "bsdiff",                   "urxvt -e sh -c 'bsdiff ; bash'" },
  { "bspatch",                  "urxvt -e sh -c 'bspatch ; bash'" },
  { "bmore",                    "urxvt -e sh -c 'bmore ; bash'" },
  { "bvedit",                   "urxvt -e sh -c 'bvedit -h ; bash'" },
  { "bvi",                      "urxvt -e sh -c 'bvi -h ; bash'" },
  { "bview",                    "urxvt -e sh -c 'bview -h ; bash'" },
  { "bytecode-viewer",          "urxvt -e sh -c 'bytecode-viewer ; bash'" },
  { "cminer",                   "urxvt -e sh -c 'cminer ; bash'" },
  { "damm",                     "urxvt -e sh -c 'damm -h ; bash'" },
  { "die",                      "urxvt -e sh -c 'die ; bash'" },
  { "diec",                     "urxvt -e sh -c 'diec ; bash'" },
  { "dexpatcher",               "urxvt -e sh -c 'dexpatcher -h ; bash'" },
  { "dissector",                "urxvt -e sh -c 'dissector -h ; bash'" },
  { "dutas",                    "urxvt -e sh -c 'dutas -h ; bash'" },
  { "dwarf",                    "urxvt -e sh -c 'dwarf --help ; bash'" },
  { "drinject",                 "urxvt -e sh -c 'drinject ; bash'" },
  { "drloader",                 "urxvt -e sh -c 'drloader ; bash'" },
  { "drrun",                    "urxvt -e sh -c 'drrun ; bash'" },
  { "nudgeunix",                "urxvt -e sh -c 'nudgeunix ; bash'" },
  { "drltrace",                 "urxvt -e sh -c 'drltrace ; bash'" },
  { "drmemory",                 "urxvt -e sh -c 'drmemory ; bash'" },
  { "symquery",                 "urxvt -e sh -c 'symquery ; bash'" },
  { "ecfs",                     "urxvt -e sh -c 'ecfs ; bash'" },
  { "ecfs-handler",             "urxvt -e sh -c 'ecfs-handler ; bash'" },
  { "et-flip",                  "urxvt -e sh -c 'et-flip ; bash'" },
  { "readecfs",                 "urxvt -e sh -c 'readecfs ; bash'" },
  { "ebfc",                     "urxvt -e sh -c 'ebfc -h ; bash'" },
  { "elfls",                    "urxvt -e sh -c 'elfls ; bash'" },
  { "elftoc",                   "urxvt -e sh -c 'elftoc --help ; bash'" },
  { "infect",                   "urxvt -e sh -c 'infect ; bash'" },
  { "objres",                   "urxvt -e sh -c 'objres --help ; bash'" },
  { "sstrip",                   "urxvt -e sh -c 'sstrip ; bash'" },
  { "ebfc",                     "urxvt -e sh -c 'ebfc -h ; bash'" },
  { "elfls",                    "urxvt -e sh -c 'elfls ; bash'" },
  { "elftoc",                   "urxvt -e sh -c 'elftoc --help ; bash'" },
  { "infect",                   "urxvt -e sh -c 'infect ; bash'" },
  { "objres",                   "urxvt -e sh -c 'objres --help ; bash'" },
  { "sstrip",                   "urxvt -e sh -c 'sstrip ; bash'" },
  { "elfparser-cli",            "urxvt -e sh -c 'elfparser-cli --help ; bash'" },
  { "eu-addr2line",             "urxvt -e sh -c 'eu-addr2line --help ; bash'" },
  { "eu-ar",                    "urxvt -e sh -c 'eu-ar --help ; bash'" },
  { "eu-elfcmp",                "urxvt -e sh -c 'eu-elfcmp --help ; bash'" },
  { "eu-elfcompress",           "urxvt -e sh -c 'eu-elfcompress --help ; bash'" },
  { "eu-elflint",               "urxvt -e sh -c 'eu-elflint --help ; bash'" },
  { "eu-findtextrel",           "urxvt -e sh -c 'eu-findtextrel --help ; bash'" },
  { "eu-make-debug-archive",    "urxvt -e sh -c 'eu-make-debug-archive --help ; bash'" },
  { "eu-nm",                    "urxvt -e sh -c 'eu-nm --help ; bash'" },
  { "eu-objdump",               "urxvt -e sh -c 'eu-objdump --help ; bash'" },
  { "eu-ranlib",                "urxvt -e sh -c 'eu-ranlib --help ; bash'" },
  { "eu-readelf",               "urxvt -e sh -c 'eu-readelf --help ; bash'" },
  { "eu-size",                  "urxvt -e sh -c 'eu-size --help ; bash'" },
  { "eu-stack",                 "urxvt -e sh -c 'eu-stack --help ; bash'" },
  { "eu-strings",               "urxvt -e sh -c 'eu-strings --help ; bash'" },
  { "eu-strip",                 "urxvt -e sh -c 'eu-strip --help ; bash'" },
  { "eu-unstrip",               "urxvt -e sh -c 'eu-unstrip --help ; bash'" },
  { "eu-addr2line",             "urxvt -e sh -c 'eu-addr2line --help ; bash'" },
  { "eu-ar",                    "urxvt -e sh -c 'eu-ar --help ; bash'" },
  { "eu-elfcmp",                "urxvt -e sh -c 'eu-elfcmp --help ; bash'" },
  { "eu-elfcompress",           "urxvt -e sh -c 'eu-elfcompress --help ; bash'" },
  { "eu-elflint",               "urxvt -e sh -c 'eu-elflint --help ; bash'" },
  { "eu-findtextrel",           "urxvt -e sh -c 'eu-findtextrel --help ; bash'" },
  { "eu-make-debug-archive",    "urxvt -e sh -c 'eu-make-debug-archive --help ; bash'" },
  { "eu-nm",                    "urxvt -e sh -c 'eu-nm --help ; bash'" },
  { "eu-objdump",               "urxvt -e sh -c 'eu-objdump --help ; bash'" },
  { "eu-ranlib",                "urxvt -e sh -c 'eu-ranlib --help ; bash'" },
  { "eu-readelf",               "urxvt -e sh -c 'eu-readelf --help ; bash'" },
  { "eu-size",                  "urxvt -e sh -c 'eu-size --help ; bash'" },
  { "eu-stack",                 "urxvt -e sh -c 'eu-stack --help ; bash'" },
  { "eu-strings",               "urxvt -e sh -c 'eu-strings --help ; bash'" },
  { "eu-strip",                 "urxvt -e sh -c 'eu-strip --help ; bash'" },
  { "eu-unstrip",               "urxvt -e sh -c 'eu-unstrip --help ; bash'" },
  { "e2dbg32",                  "urxvt -e sh -c 'e2dbg32 ; bash'" },
  { "e2dbg64",                  "urxvt -e sh -c 'e2dbg64 ; bash'" },
  { "etrace32",                 "urxvt -e sh -c 'etrace32 ; bash'" },
  { "etrace64",                 "urxvt -e sh -c 'etrace64 ; bash'" },
  { "evarista32",               "urxvt -e sh -c 'evarista32 ; bash'" },
  { "evarista64",               "urxvt -e sh -c 'evarista64 ; bash'" },
  { "kedbg32",                  "urxvt -e sh -c 'kedbg32 ; bash'" },
  { "kedbg64",                  "urxvt -e sh -c 'kedbg64 ; bash'" },
  { "evilize",                  "urxvt -e sh -c 'evilize -h ; bash'" },
  { "exe2image",                "urxvt -e sh -c 'exe2image ; bash'" },
  { "exescan",                  "urxvt -e sh -c 'exescan ; bash'" },
  { "expimp-lookup",            "urxvt -e sh -c 'expimp-lookup ; bash'" },
  { "expose",                   "urxvt -e sh -c 'expose ; bash'" },
  { "acorn",                    "urxvt -e sh -c 'acorn ; bash'" },
  { "compress",                 "urxvt -e sh -c 'compress ; bash'" },
  { "lint",                     "urxvt -e sh -c 'lint ; bash'" },
  { "release",                  "urxvt -e sh -c 'release ; bash'" },
  { "source-highlight",         "urxvt -e sh -c 'source-highlight ; bash'" },
  { ".coverrc",                 "urxvt -e sh -c '.coverrc ; bash'" },
  { "cover",                    "urxvt -e sh -c 'cover ; bash'" },
  { "which",                    "urxvt -e sh -c 'which ; bash'" },
  { "acorn",                    "urxvt -e sh -c 'acorn ; bash'" },
  { "test262.whitelist",        "urxvt -e sh -c 'test262.whitelist ; bash'" },
  { "acorn",                    "urxvt -e sh -c 'acorn ; bash'" },
  { "jsesc",                    "urxvt -e sh -c 'jsesc ; bash'" },
  { "ncp",                      "urxvt -e sh -c 'ncp ; bash'" },
  { "which",                    "urxvt -e sh -c 'which ; bash'" },
  { "parser",                   "urxvt -e sh -c 'parser ; bash'" },
  { "jsesc",                    "urxvt -e sh -c 'jsesc ; bash'" },
  { "semver",                   "urxvt -e sh -c 'semver ; bash'" },
  { "uuid",                     "urxvt -e sh -c 'uuid ; bash'" },
  { "which",                    "urxvt -e sh -c 'which ; bash'" },
  { "acorn",                    "urxvt -e sh -c 'acorn ; bash'" },
  { "compress",                 "urxvt -e sh -c 'compress ; bash'" },
  { "lint",                     "urxvt -e sh -c 'lint ; bash'" },
  { "release",                  "urxvt -e sh -c 'release ; bash'" },
  { "source-highlight",         "urxvt -e sh -c 'source-highlight ; bash'" },
  { ".coverrc",                 "urxvt -e sh -c '.coverrc ; bash'" },
  { "cover",                    "urxvt -e sh -c 'cover ; bash'" },
  { "which",                    "urxvt -e sh -c 'which ; bash'" },
  { "acorn",                    "urxvt -e sh -c 'acorn ; bash'" },
  { "test262.whitelist",        "urxvt -e sh -c 'test262.whitelist ; bash'" },
  { "acorn",                    "urxvt -e sh -c 'acorn ; bash'" },
  { "jsesc",                    "urxvt -e sh -c 'jsesc ; bash'" },
  { "ncp",                      "urxvt -e sh -c 'ncp ; bash'" },
  { "which",                    "urxvt -e sh -c 'which ; bash'" },
  { "parser",                   "urxvt -e sh -c 'parser ; bash'" },
  { "jsesc",                    "urxvt -e sh -c 'jsesc ; bash'" },
  { "semver",                   "urxvt -e sh -c 'semver ; bash'" },
  { "uuid",                     "urxvt -e sh -c 'uuid ; bash'" },
  { "which",                    "urxvt -e sh -c 'which ; bash'" },
  { "semver",                   "urxvt -e sh -c 'semver ; bash'" },
  { "uuid",                     "urxvt -e sh -c 'uuid ; bash'" },
  { "jsesc",                    "urxvt -e sh -c 'jsesc ; bash'" },
  { "parser",                   "urxvt -e sh -c 'parser ; bash'" },
  { "jsesc",                    "urxvt -e sh -c 'jsesc ; bash'" },
  { "acorn",                    "urxvt -e sh -c 'acorn ; bash'" },
  { "jsesc",                    "urxvt -e sh -c 'jsesc ; bash'" },
  { "parser",                   "urxvt -e sh -c 'parser ; bash'" },
  { "jsesc",                    "urxvt -e sh -c 'jsesc ; bash'" },
  { "semver",                   "urxvt -e sh -c 'semver ; bash'" },
  { "which",                    "urxvt -e sh -c 'which ; bash'" },
  { "frida-ios-dump",           "urxvt -e sh -c 'frida-ios-dump -h ; bash'" },
  { "gadgetinspector",          "urxvt -e sh -c 'gadgetinspector ; bash'" },
  { "gdbgui",                   "urxvt -e sh -c 'gdbgui -h ; bash'" },
  { "haystack-find-heap",       "urxvt -e sh -c 'haystack-find-heap ; bash'" },
  { "haystack-live-dump",       "urxvt -e sh -c 'haystack-live-dump ; bash'" },
  { "haystack-live-watch",      "urxvt -e sh -c 'haystack-live-watch ; bash'" },
  { "haystack-rekall-dump",     "urxvt -e sh -c 'haystack-rekall-dump ; bash'" },
  { "haystack-search",          "urxvt -e sh -c 'haystack-search ; bash'" },
  { "haystack-volatility-dump", "urxvt -e sh -c 'haystack-volatility-dump ; bash'" },
  { "hercules-payload",         "urxvt -e sh -c 'hercules-payload ; bash'" },
  { "hopper",                   "urxvt -e sh -c 'hopper ; bash'" },
  { "jpegdump",                 "urxvt -e sh -c 'jpegdump -h ; bash'" },
  { "jwscan",                   "urxvt -e sh -c 'jwscan -h ; bash'" },
  { "gen-bout",                 "urxvt -e sh -c 'gen-bout ; bash'" },
  { "gen-random-bout",          "urxvt -e sh -c 'gen-random-bout ; bash'" },
  { "kleaver",                  "urxvt -e sh -c 'kleaver -h ; bash'" },
  { "klee",                     "urxvt -e sh -c 'klee -h ; bash'" },
  { "klee-stats",               "urxvt -e sh -c 'klee-stats -h ; bash'" },
  { "ktest-tool",               "urxvt -e sh -c 'ktest-tool -h ; bash'" },
  { "lazydroid",                "urxvt -e sh -c 'lazydroid ; bash'" },
  { "interpatch",               "urxvt -e sh -c 'interpatch -h ; bash'" },
  { "leena",                    "urxvt -e sh -c 'leena ; bash'" },
  { "acorn",                    "urxvt -e sh -c 'acorn ; bash'" },
  { "cake",                     "urxvt -e sh -c 'cake ; bash'" },
  { "coffee",                   "urxvt -e sh -c 'coffee ; bash'" },
  { "grunt",                    "urxvt -e sh -c 'grunt ; bash'" },
  { "which",                    "urxvt -e sh -c 'which ; bash'" },
  { "ncp",                      "urxvt -e sh -c 'ncp ; bash'" },
  { "tsc",                      "urxvt -e sh -c 'tsc ; bash'" },
  { "tsserver",                 "urxvt -e sh -c 'tsserver ; bash'" },
  { "which",                    "urxvt -e sh -c 'which ; bash'" },
  { "handlebars",               "urxvt -e sh -c 'handlebars ; bash'" },
  { "client",                   "urxvt -e sh -c 'client ; bash'" },
  { "ncp",                      "urxvt -e sh -c 'ncp ; bash'" },
  { "semver",                   "urxvt -e sh -c 'semver ; bash'" },
  { "tsc",                      "urxvt -e sh -c 'tsc ; bash'" },
  { "tsserver",                 "urxvt -e sh -c 'tsserver ; bash'" },
  { "which",                    "urxvt -e sh -c 'which ; bash'" },
  { "acorn",                    "urxvt -e sh -c 'acorn ; bash'" },
  { "without_eval",             "urxvt -e sh -c 'without_eval ; bash'" },
  { "linux-inject",             "urxvt -e sh -c 'linux-inject -h ; bash'" },
  { "linux-inject-32",          "urxvt -e sh -c 'linux-inject-32 -h ; bash'" },
  { "mpclient",                 "urxvt -e sh -c 'mpclient ; bash'" },
  { "ltrace",                   "urxvt -e sh -c 'ltrace ; bash'" },
  { "malscan",                  "urxvt -e sh -c 'malscan ; bash'" },
  { "manticore",                "urxvt -e sh -c 'manticore -h ; bash'" },
  { "manticore-verifier",       "urxvt -e sh -c 'manticore-verifier ; bash'" },
  { "manul",                    "urxvt -e sh -c 'manul -h ; bash'" },
  { "pindb",                    "urxvt -e sh -c 'pindb ; bash'" },
  { "melkor",                   "urxvt -e sh -c 'melkor -h ; bash'" },
  { "metame",                   "urxvt -e sh -c 'metame -h ; bash'" },
  { "createnpk",                "urxvt -e sh -c 'createnpk ; bash'" },
  { "dumpnpk",                  "urxvt -e sh -c 'dumpnpk ; bash'" },
  { "unpacknpk",                "urxvt -e sh -c 'unpacknpk ; bash'" },
  { "ms-sys",                   "urxvt -e sh -c 'ms-sys -h ; bash'" },
  { "msvpwn",                   "urxvt -e sh -c 'msvpwn -h ; bash'" },
  { "objection",                "urxvt -e sh -c 'objection --help ; bash'" },
  { "oledump",                  "urxvt -e sh -c 'oledump -h ; bash'" },
  { "osslsigncode",             "urxvt -e sh -c 'osslsigncode -h ; bash'" },
  { "packer",                   "urxvt -e sh -c 'packer ; bash'" },
  { "packerid",                 "urxvt -e sh -c 'packerid -h ; bash'" },
  { "patchkit",                 "urxvt -e sh -c 'patchkit -h ; bash'" },
  { "peframe",                  "urxvt -e sh -c 'peframe ; bash'" },
  { "pepper",                   "urxvt -e sh -c 'pepper -h ; bash'" },
  { "pin",                      "urxvt -e sh -c 'pin ; bash'" },
  { "pindb",                    "urxvt -e sh -c 'pindb ; bash'" },
  { "pindb.sig",                "urxvt -e sh -c 'pindb.sig ; bash'" },
  { "pindb",                    "urxvt -e sh -c 'pindb ; bash'" },
  { "pindb.sig",                "urxvt -e sh -c 'pindb.sig ; bash'" },
  { "pintool",                  "urxvt -e sh -c 'pintool -h ; bash'" },
  { "pintool2",                 "urxvt -e sh -c 'pintool2 -h ; bash'" },
  { "pixd",                     "urxvt -e sh -c 'pixd -h ; bash'" },
  { "plasma-disasm",            "urxvt -e sh -c 'plasma-disasm -h ; bash'" },
  { "powerstager",              "urxvt -e sh -c 'powerstager -h ; bash'" },
  { "procdump",                 "urxvt -e sh -c 'procdump ; bash'" },
  { "proctal",                  "urxvt -e sh -c 'proctal -h ; bash'" },
  { "frida",                    "urxvt -e sh -c 'frida -h ; bash'" },
  { "frida-create",             "urxvt -e sh -c 'frida-create ; bash'" },
  { "frida-discover",           "urxvt -e sh -c 'frida-discover -h ; bash'" },
  { "frida-join",               "urxvt -e sh -c 'frida-join ; bash'" },
  { "frida-kill",               "urxvt -e sh -c 'frida-kill -h ; bash'" },
  { "frida-ls-devices",         "urxvt -e sh -c 'frida-ls-devices -h ; bash'" },
  { "frida-trace",              "urxvt -e sh -c 'frida-trace -h ; bash'" },
  { "ezhexviewer",              "urxvt -e sh -c 'ezhexviewer ; bash'" },
  { "ftguess",                  "urxvt -e sh -c 'ftguess ; bash'" },
  { "mraptor",                  "urxvt -e sh -c 'mraptor ; bash'" },
  { "msodde",                   "urxvt -e sh -c 'msodde ; bash'" },
  { "olebrowse",                "urxvt -e sh -c 'olebrowse ; bash'" },
  { "oledir",                   "urxvt -e sh -c 'oledir ; bash'" },
  { "olefile",                  "urxvt -e sh -c 'olefile ; bash'" },
  { "oleid",                    "urxvt -e sh -c 'oleid -h ; bash'" },
  { "olemap",                   "urxvt -e sh -c 'olemap ; bash'" },
  { "olemeta",                  "urxvt -e sh -c 'olemeta -h ; bash'" },
  { "oleobj",                   "urxvt -e sh -c 'oleobj ; bash'" },
  { "oletimes",                 "urxvt -e sh -c 'oletimes ; bash'" },
  { "olevba",                   "urxvt -e sh -c 'olevba ; bash'" },
  { "pyxswf",                   "urxvt -e sh -c 'pyxswf ; bash'" },
  { "rtfobj",                   "urxvt -e sh -c 'rtfobj ; bash'" },
  { "frida-create2",            "urxvt -e sh -c 'frida-create2 ; bash'" },
  { "frida-discover2",          "urxvt -e sh -c 'frida-discover2 ; bash'" },
  { "frida-join2",              "urxvt -e sh -c 'frida-join2 ; bash'" },
  { "frida-kill2",              "urxvt -e sh -c 'frida-kill2 ; bash'" },
  { "frida-ls-devices2",        "urxvt -e sh -c 'frida-ls-devices2 ; bash'" },
  { "frida-trace2",             "urxvt -e sh -c 'frida-trace2 ; bash'" },
  { "frida2",                   "urxvt -e sh -c 'frida2 ; bash'" },
  { "ezhexviewer2",             "urxvt -e sh -c 'ezhexviewer2 ; bash'" },
  { "ftguess2",                 "urxvt -e sh -c 'ftguess2 ; bash'" },
  { "mraptor2",                 "urxvt -e sh -c 'mraptor2 ; bash'" },
  { "msodde2",                  "urxvt -e sh -c 'msodde2 ; bash'" },
  { "olebrowse2",               "urxvt -e sh -c 'olebrowse2 ; bash'" },
  { "oledir2",                  "urxvt -e sh -c 'oledir2 ; bash'" },
  { "olefile2",                 "urxvt -e sh -c 'olefile2 ; bash'" },
  { "oleid2",                   "urxvt -e sh -c 'oleid2 ; bash'" },
  { "olemap2",                  "urxvt -e sh -c 'olemap2 ; bash'" },
  { "olemeta2",                 "urxvt -e sh -c 'olemeta2 ; bash'" },
  { "oleobj2",                  "urxvt -e sh -c 'oleobj2 ; bash'" },
  { "oletimes2",                "urxvt -e sh -c 'oletimes2 ; bash'" },
  { "olevba2",                  "urxvt -e sh -c 'olevba2 ; bash'" },
  { "pyxswf2",                  "urxvt -e sh -c 'pyxswf2 ; bash'" },
  { "rtfobj2",                  "urxvt -e sh -c 'rtfobj2 ; bash'" },
  { "quickscope",               "urxvt -e sh -c 'quickscope -h ; bash'" },
  { "rbasefind",                "urxvt -e sh -c 'rbasefind -h ; bash'" },
  { "recomposer",               "urxvt -e sh -c 'recomposer -h ; bash'" },
  { "redress",                  "urxvt -e sh -c 'redress -h ; bash'" },
  { "ropper",                   "urxvt -e sh -c 'ropper ; bash'" },
  { "rp-lin-x64",               "urxvt -e sh -c 'rp-lin-x64 -h ; bash'" },
  { "saruman",                  "urxvt -e sh -c 'saruman ; bash'" },
  { "sea",                      "urxvt -e sh -c 'sea -h ; bash'" },
  { "sgn",                      "urxvt -e sh -c 'sgn ; bash'" },
  { "sherlocked",               "urxvt -e sh -c 'sherlocked ; bash'" },
  { "stripx",                   "urxvt -e sh -c 'stripx ; bash'" },
  { "stub",                     "urxvt -e sh -c 'stub ; bash'" },
  { "smap",                     "urxvt -e sh -c 'smap -h ; bash'" },
  { "soot",                     "urxvt -e sh -c 'soot -h ; bash'" },
  { "strace",                   "urxvt -e sh -c 'strace ; bash'" },
  { "strace-log-merge",         "urxvt -e sh -c 'strace-log-merge ; bash'" },
  { "strace",                   "urxvt -e sh -c 'strace ; bash'" },
  { "strace-log-merge",         "urxvt -e sh -c 'strace-log-merge ; bash'" },
  { "flarestrings",             "urxvt -e sh -c 'flarestrings -h ; bash'" },
  { "rank_strings",             "urxvt -e sh -c 'rank_strings -h ; bash'" },
  { "as3compile",               "urxvt -e sh -c 'as3compile ; bash'" },
  { "font2swf",                 "urxvt -e sh -c 'font2swf ; bash'" },
  { "gif2swf",                  "urxvt -e sh -c 'gif2swf ; bash'" },
  { "jpeg2swf",                 "urxvt -e sh -c 'jpeg2swf ; bash'" },
  { "pdf2swf",                  "urxvt -e sh -c 'pdf2swf ; bash'" },
  { "png2swf",                  "urxvt -e sh -c 'png2swf ; bash'" },
  { "swfbbox",                  "urxvt -e sh -c 'swfbbox ; bash'" },
  { "swfc",                     "urxvt -e sh -c 'swfc ; bash'" },
  { "swfdump",                  "urxvt -e sh -c 'swfdump ; bash'" },
  { "swfextract",               "urxvt -e sh -c 'swfextract ; bash'" },
  { "swfrender",                "urxvt -e sh -c 'swfrender ; bash'" },
  { "swfstrings",               "urxvt -e sh -c 'swfstrings ; bash'" },
  { "wav2swf",                  "urxvt -e sh -c 'wav2swf ; bash'" },
  { "trid",                     "urxvt -e sh -c 'trid -h ; bash'" },
  { "truegaze",                 "urxvt -e sh -c 'truegaze -h ; bash'" },
  { "unifuzzer",                "urxvt -e sh -c 'unifuzzer ; bash'" },
  { "unstrip",                  "urxvt -e sh -c 'unstrip ; bash'" },
  { "upx",                      "urxvt -e sh -c 'upx -h ; bash'" },
  { "callgrind_annotate",       "urxvt -e sh -c 'callgrind_annotate ; bash'" },
  { "callgrind_control",        "urxvt -e sh -c 'callgrind_control ; bash'" },
  { "cg_annotate",              "urxvt -e sh -c 'cg_annotate ; bash'" },
  { "cg_diff",                  "urxvt -e sh -c 'cg_diff ; bash'" },
  { "cg_merge",                 "urxvt -e sh -c 'cg_merge ; bash'" },
  { "ms_print",                 "urxvt -e sh -c 'ms_print ; bash'" },
  { "valgrind",                 "urxvt -e sh -c 'valgrind ; bash'" },
  { "valgrind-di-server",       "urxvt -e sh -c 'valgrind-di-server ; bash'" },
  { "valgrind-listener",        "urxvt -e sh -c 'valgrind-listener ; bash'" },
  { "vgdb",                     "urxvt -e sh -c 'vgdb ; bash'" },
  { "callgrind_annotate",       "urxvt -e sh -c 'callgrind_annotate ; bash'" },
  { "callgrind_control",        "urxvt -e sh -c 'callgrind_control ; bash'" },
  { "cg_annotate",              "urxvt -e sh -c 'cg_annotate ; bash'" },
  { "cg_diff",                  "urxvt -e sh -c 'cg_diff ; bash'" },
  { "cg_merge",                 "urxvt -e sh -c 'cg_merge ; bash'" },
  { "ms_print",                 "urxvt -e sh -c 'ms_print ; bash'" },
  { "valgrind",                 "urxvt -e sh -c 'valgrind ; bash'" },
  { "valgrind-di-server",       "urxvt -e sh -c 'valgrind-di-server ; bash'" },
  { "valgrind-listener",        "urxvt -e sh -c 'valgrind-listener ; bash'" },
  { "vgdb",                     "urxvt -e sh -c 'vgdb ; bash'" },
  { "veles",                    "urxvt -e sh -c 'veles ; bash'" },
  { "viper",                    "urxvt -e sh -c 'viper -h ; bash'" },
  { "volafox",                  "urxvt -e sh -c 'volafox -h ; bash'" },
  { "wcc",                      "urxvt -e sh -c 'wcc -h ; bash'" },
  { "wcch",                     "urxvt -e sh -c 'wcch -h ; bash'" },
  { "wld",                      "urxvt -e sh -c 'wld -h ; bash'" },
  { "wldd",                     "urxvt -e sh -c 'wldd -h ; bash'" },
  { "wxHexEditor",              "urxvt -e sh -c 'wxHexEditor ; bash'" },
  { "zelos",                    "urxvt -e sh -c 'zelos -h ; bash'" },
}

return binarymenu
