bluetoothmenu = {
  { "bleah",               "urxvt -e sh -c 'bleah -h ; bash'" },
  { "blue-hydra",          "urxvt -e sh -c 'blue-hydra -h ; bash'" },
  { "blue_hydra",          "urxvt -e sh -c 'blue_hydra ; bash'" },
  { "rfkill-reset",        "urxvt -e sh -c 'rfkill-reset ; bash'" },
  { "test-discovery",      "urxvt -e sh -c 'test-discovery ; bash'" },
  { "bluebugger",          "urxvt -e sh -c 'bluebugger -h ; bash'" },
  { "attest",              "urxvt -e sh -c 'attest ; bash'" },
  { "bluediving-bdaddr",   "urxvt -e sh -c 'bluediving-bdaddr ; bash'" },
  { "btftp",               "urxvt -e sh -c 'btftp ; bash'" },
  { "btobex",              "urxvt -e sh -c 'btobex ; bash'" },
  { "hstest",              "urxvt -e sh -c 'hstest ; bash'" },
  { "l2cap-packet",        "urxvt -e sh -c 'l2cap-packet ; bash'" },
  { "bluefog",             "urxvt -e sh -c 'bluefog ; bash'" },
  { "bluelog",             "urxvt -e sh -c 'bluelog -h ; bash'" },
  { "bluepot",             "urxvt -e sh -c 'bluepot ; bash'" },
  { "blueprint",           "urxvt -e sh -c 'blueprint -h ; bash'" },
  { "blueranger",          "urxvt -e sh -c 'blueranger ; bash'" },
  { "bluescan",            "urxvt -e sh -c 'bluescan ; bash'" },
  { "bluesnarfer",         "urxvt -e sh -c 'bluesnarfer -h ; bash'" },
  { "braces",              "urxvt -e sh -c 'braces -h ; bash'" },
  { "bss",                 "urxvt -e sh -c 'bss -h ; bash'" },
  { "psm_scan",            "urxvt -e sh -c 'psm_scan -h ; bash'" },
  { "rfcomm_scan",         "urxvt -e sh -c 'rfcomm_scan -h ; bash'" },
  { "btlejack",            "urxvt -e sh -c 'btlejack ; bash'" },
  { "btproxy-mitm",        "urxvt -e sh -c 'btproxy-mitm -h ; bash'" },
  { "btscanner",           "urxvt -e sh -c 'btscanner --help ; bash'" },
  { "carwhisperer",        "urxvt -e sh -c 'carwhisperer -h ; bash'" },
  { "crackle",             "urxvt -e sh -c 'crackle ; bash'" },
  { "fl0p",                "urxvt -e sh -c 'fl0p -h ; bash'" },
  { "ghettotooth",         "urxvt -e sh -c 'ghettotooth ; bash'" },
  { "hidattack",           "urxvt -e sh -c 'hidattack -h ; bash'" },
  { "obexstress",          "urxvt -e sh -c 'obexstress -h ; bash'" },
  { "redfang",             "urxvt -e sh -c 'redfang --help ; bash'" },
  { "spooftooph",          "urxvt -e sh -c 'spooftooph -h ; bash'" },
  { "tanya",               "urxvt -e sh -c 'tanya ; bash'" },
  { "tbear",               "urxvt -e sh -c 'tbear -h ; bash'" },
  { "tbsearch",            "urxvt -e sh -c 'tbsearch ; bash'" },
  { "ubertooth-afh",       "urxvt -e sh -c 'ubertooth-afh ; bash'" },
  { "ubertooth-btbr",      "urxvt -e sh -c 'ubertooth-btbr ; bash'" },
  { "ubertooth-btle",      "urxvt -e sh -c 'ubertooth-btle -h ; bash'" },
  { "ubertooth-debug",     "urxvt -e sh -c 'ubertooth-debug ; bash'" },
  { "ubertooth-dfu",       "urxvt -e sh -c 'ubertooth-dfu ; bash'" },
  { "ubertooth-ducky",     "urxvt -e sh -c 'ubertooth-ducky ; bash'" },
  { "ubertooth-dump",      "urxvt -e sh -c 'ubertooth-dump -h ; bash'" },
  { "ubertooth-ego",       "urxvt -e sh -c 'ubertooth-ego ; bash'" },
  { "ubertooth-follow",    "urxvt -e sh -c 'ubertooth-follow -h ; bash'" },
  { "ubertooth-rx",        "urxvt -e sh -c 'ubertooth-rx ; bash'" },
  { "ubertooth-scan",      "urxvt -e sh -c 'ubertooth-scan ; bash'" },
  { "ubertooth-specan",    "urxvt -e sh -c 'ubertooth-specan -h ; bash'" },
  { "ubertooth-specan-ui", "urxvt -e sh -c 'ubertooth-specan-ui ; bash'" },
  { "ubertooth-tx",        "urxvt -e sh -c 'ubertooth-tx ; bash'" },
  { "ubertooth-util",      "urxvt -e sh -c 'ubertooth-util -h ; bash'" },
}

return bluetoothmenu
