codeauditmenu = {
  { "androwarn",                    "urxvt -e sh -c 'androwarn -h ; bash'" },
  { "bof-detector",                 "urxvt -e sh -c 'bof-detector -h ; bash'" },
  { "brakeman",                     "urxvt -e sh -c 'brakeman ; bash'" },
  { "cflow",                        "urxvt -e sh -c 'cflow -h ; bash'" },
  { "codeql",                       "urxvt -e sh -c 'codeql ; bash'" },
  { "java",                         "urxvt -e sh -c 'java ; bash'" },
  { "javac",                        "urxvt -e sh -c 'javac ; bash'" },
  { "keytool",                      "urxvt -e sh -c 'keytool ; bash'" },
  { "rmid",                         "urxvt -e sh -c 'rmid ; bash'" },
  { "rmiregistry",                  "urxvt -e sh -c 'rmiregistry ; bash'" },
  { "serialver",                    "urxvt -e sh -c 'serialver ; bash'" },
  { "tsc",                          "urxvt -e sh -c 'tsc ; bash'" },
  { "tsserver",                     "urxvt -e sh -c 'tsserver ; bash'" },
  { "java",                         "urxvt -e sh -c 'java ; bash'" },
  { "javac",                        "urxvt -e sh -c 'javac ; bash'" },
  { "keytool",                      "urxvt -e sh -c 'keytool ; bash'" },
  { "rmid",                         "urxvt -e sh -c 'rmid ; bash'" },
  { "rmiregistry",                  "urxvt -e sh -c 'rmiregistry ; bash'" },
  { "serialver",                    "urxvt -e sh -c 'serialver ; bash'" },
  { "cppcheck",                     "urxvt -e sh -c 'cppcheck -h ; bash'" },
  { "cppcheck-gui",                 "urxvt -e sh -c 'cppcheck-gui ; bash'" },
  { "cppcheck-htmlreport",          "urxvt -e sh -c 'cppcheck-htmlreport -h ; bash'" },
  { "cppcheck",                     "urxvt -e sh -c 'cppcheck -h ; bash'" },
  { "cppcheck-gui",                 "urxvt -e sh -c 'cppcheck-gui ; bash'" },
  { "cppcheck-htmlreport",          "urxvt -e sh -c 'cppcheck-htmlreport -h ; bash'" },
  { "detect-secrets",               "urxvt -e sh -c 'detect-secrets -h ; bash'" },
  { "detect-secrets-hook",          "urxvt -e sh -c 'detect-secrets-hook -h ; bash'" },
  { "devaudit",                     "urxvt -e sh -c 'devaudit -h ; bash'" },
  { "dscanner",                     "urxvt -e sh -c 'dscanner -h ; bash'" },
  { "expose",                       "urxvt -e sh -c 'expose ; bash'" },
  { "acorn",                        "urxvt -e sh -c 'acorn ; bash'" },
  { "compress",                     "urxvt -e sh -c 'compress ; bash'" },
  { "lint",                         "urxvt -e sh -c 'lint ; bash'" },
  { "release",                      "urxvt -e sh -c 'release ; bash'" },
  { "source-highlight",             "urxvt -e sh -c 'source-highlight ; bash'" },
  { ".coverrc",                     "urxvt -e sh -c '.coverrc ; bash'" },
  { "cover",                        "urxvt -e sh -c 'cover ; bash'" },
  { "which",                        "urxvt -e sh -c 'which ; bash'" },
  { "acorn",                        "urxvt -e sh -c 'acorn ; bash'" },
  { "test262.whitelist",            "urxvt -e sh -c 'test262.whitelist ; bash'" },
  { "acorn",                        "urxvt -e sh -c 'acorn ; bash'" },
  { "jsesc",                        "urxvt -e sh -c 'jsesc ; bash'" },
  { "ncp",                          "urxvt -e sh -c 'ncp ; bash'" },
  { "which",                        "urxvt -e sh -c 'which ; bash'" },
  { "parser",                       "urxvt -e sh -c 'parser ; bash'" },
  { "jsesc",                        "urxvt -e sh -c 'jsesc ; bash'" },
  { "semver",                       "urxvt -e sh -c 'semver ; bash'" },
  { "uuid",                         "urxvt -e sh -c 'uuid ; bash'" },
  { "which",                        "urxvt -e sh -c 'which ; bash'" },
  { "acorn",                        "urxvt -e sh -c 'acorn ; bash'" },
  { "compress",                     "urxvt -e sh -c 'compress ; bash'" },
  { "lint",                         "urxvt -e sh -c 'lint ; bash'" },
  { "release",                      "urxvt -e sh -c 'release ; bash'" },
  { "source-highlight",             "urxvt -e sh -c 'source-highlight ; bash'" },
  { ".coverrc",                     "urxvt -e sh -c '.coverrc ; bash'" },
  { "cover",                        "urxvt -e sh -c 'cover ; bash'" },
  { "which",                        "urxvt -e sh -c 'which ; bash'" },
  { "acorn",                        "urxvt -e sh -c 'acorn ; bash'" },
  { "test262.whitelist",            "urxvt -e sh -c 'test262.whitelist ; bash'" },
  { "acorn",                        "urxvt -e sh -c 'acorn ; bash'" },
  { "jsesc",                        "urxvt -e sh -c 'jsesc ; bash'" },
  { "ncp",                          "urxvt -e sh -c 'ncp ; bash'" },
  { "which",                        "urxvt -e sh -c 'which ; bash'" },
  { "parser",                       "urxvt -e sh -c 'parser ; bash'" },
  { "jsesc",                        "urxvt -e sh -c 'jsesc ; bash'" },
  { "semver",                       "urxvt -e sh -c 'semver ; bash'" },
  { "uuid",                         "urxvt -e sh -c 'uuid ; bash'" },
  { "which",                        "urxvt -e sh -c 'which ; bash'" },
  { "semver",                       "urxvt -e sh -c 'semver ; bash'" },
  { "uuid",                         "urxvt -e sh -c 'uuid ; bash'" },
  { "jsesc",                        "urxvt -e sh -c 'jsesc ; bash'" },
  { "parser",                       "urxvt -e sh -c 'parser ; bash'" },
  { "jsesc",                        "urxvt -e sh -c 'jsesc ; bash'" },
  { "acorn",                        "urxvt -e sh -c 'acorn ; bash'" },
  { "jsesc",                        "urxvt -e sh -c 'jsesc ; bash'" },
  { "parser",                       "urxvt -e sh -c 'parser ; bash'" },
  { "jsesc",                        "urxvt -e sh -c 'jsesc ; bash'" },
  { "semver",                       "urxvt -e sh -c 'semver ; bash'" },
  { "which",                        "urxvt -e sh -c 'which ; bash'" },
  { "flawfinder",                   "urxvt -e sh -c 'flawfinder -h ; bash'" },
  { "git-dump",                     "urxvt -e sh -c 'git-dump ; bash'" },
  { "graudit",                      "urxvt -e sh -c 'graudit -h ; bash'" },
  { "leena",                        "urxvt -e sh -c 'leena ; bash'" },
  { "acorn",                        "urxvt -e sh -c 'acorn ; bash'" },
  { "cake",                         "urxvt -e sh -c 'cake ; bash'" },
  { "coffee",                       "urxvt -e sh -c 'coffee ; bash'" },
  { "grunt",                        "urxvt -e sh -c 'grunt ; bash'" },
  { "which",                        "urxvt -e sh -c 'which ; bash'" },
  { "ncp",                          "urxvt -e sh -c 'ncp ; bash'" },
  { "tsc",                          "urxvt -e sh -c 'tsc ; bash'" },
  { "tsserver",                     "urxvt -e sh -c 'tsserver ; bash'" },
  { "which",                        "urxvt -e sh -c 'which ; bash'" },
  { "handlebars",                   "urxvt -e sh -c 'handlebars ; bash'" },
  { "client",                       "urxvt -e sh -c 'client ; bash'" },
  { "ncp",                          "urxvt -e sh -c 'ncp ; bash'" },
  { "semver",                       "urxvt -e sh -c 'semver ; bash'" },
  { "tsc",                          "urxvt -e sh -c 'tsc ; bash'" },
  { "tsserver",                     "urxvt -e sh -c 'tsserver ; bash'" },
  { "which",                        "urxvt -e sh -c 'which ; bash'" },
  { "acorn",                        "urxvt -e sh -c 'acorn ; bash'" },
  { "without_eval",                 "urxvt -e sh -c 'without_eval ; bash'" },
  { "mosca",                        "urxvt -e sh -c 'mosca ; bash'" },
  { "peach-fuzz",                   "urxvt -e sh -c 'peach-fuzz -h ; bash'" },
  { "codequery",                    "urxvt -e sh -c 'codequery ; bash'" },
  { "codeslicer",                   "urxvt -e sh -c 'codeslicer ; bash'" },
  { "pfff",                         "urxvt -e sh -c 'pfff ; bash'" },
  { "pfff_db",                      "urxvt -e sh -c 'pfff_db ; bash'" },
  { "pfff_test",                    "urxvt -e sh -c 'pfff_test ; bash'" },
  { "scheck",                       "urxvt -e sh -c 'scheck ; bash'" },
  { "sgrep",                        "urxvt -e sh -c 'sgrep ; bash'" },
  { "spatch",                       "urxvt -e sh -c 'spatch ; bash'" },
  { "stags",                        "urxvt -e sh -c 'stags ; bash'" },
  { "console",                      "urxvt -e sh -c 'console ; bash'" },
  { "procyon",                      "urxvt -e sh -c 'procyon ; bash'" },
  { "pscan",                        "urxvt -e sh -c 'pscan -h ; bash'" },
  { "rats",                         "urxvt -e sh -c 'rats -h ; bash'" },
  { "retire",                       "urxvt -e sh -c 'retire -h ; bash'" },
  { "shellcheck",                   "urxvt -e sh -c 'shellcheck ; bash'" },
  { "slither",                      "urxvt -e sh -c 'slither -h ; bash'" },
  { "slither-check-erc",            "urxvt -e sh -c 'slither-check-erc ; bash'" },
  { "slither-check-kspec",          "urxvt -e sh -c 'slither-check-kspec ; bash'" },
  { "slither-check-upgradeability", "urxvt -e sh -c 'slither-check-upgradeability ; bash'" },
  { "slither-find-paths",           "urxvt -e sh -c 'slither-find-paths ; bash'" },
  { "slither-flat",                 "urxvt -e sh -c 'slither-flat ; bash'" },
  { "slither-format",               "urxvt -e sh -c 'slither-format ; bash'" },
  { "slither-mutate",               "urxvt -e sh -c 'slither-mutate ; bash'" },
  { "slither-simil",                "urxvt -e sh -c 'slither-simil ; bash'" },
  { "smalisca",                     "urxvt -e sh -c 'smalisca --help ; bash'" },
  { "snyk",                         "urxvt -e sh -c 'snyk -h ; bash'" },
  { "spaf",                         "urxvt -e sh -c 'spaf -h ; bash'" },
  { "genflagcodes",                 "urxvt -e sh -c 'genflagcodes ; bash'" },
  { "spotbugs",                     "urxvt -e sh -c 'spotbugs -h ; bash'" },
  { "addMessages",                  "urxvt -e sh -c 'addMessages ; bash'" },
  { "computeBugHistory",            "urxvt -e sh -c 'computeBugHistory ; bash'" },
  { "convertXmlToText",             "urxvt -e sh -c 'convertXmlToText ; bash'" },
  { "defectDensity",                "urxvt -e sh -c 'defectDensity ; bash'" },
  { "fb",                           "urxvt -e sh -c 'fb ; bash'" },
  { "fbwrap",                       "urxvt -e sh -c 'fbwrap ; bash'" },
  { "filterBugs",                   "urxvt -e sh -c 'filterBugs ; bash'" },
  { "findbugs-msv",                 "urxvt -e sh -c 'findbugs-msv ; bash'" },
  { "listBugDatabaseInfo",          "urxvt -e sh -c 'listBugDatabaseInfo ; bash'" },
  { "mineBugHistory",               "urxvt -e sh -c 'mineBugHistory ; bash'" },
  { "printAppVersion",              "urxvt -e sh -c 'printAppVersion ; bash'" },
  { "printClass",                   "urxvt -e sh -c 'printClass ; bash'" },
  { "setBugDatabaseInfo",           "urxvt -e sh -c 'setBugDatabaseInfo ; bash'" },
  { "spotbugs",                     "urxvt -e sh -c 'spotbugs -h ; bash'" },
  { "spotbugs.ico",                 "urxvt -e sh -c 'spotbugs.ico ; bash'" },
  { "spotbugs2",                    "urxvt -e sh -c 'spotbugs2 ; bash'" },
  { "unionBugs",                    "urxvt -e sh -c 'unionBugs ; bash'" },
  { "xpathFind",                    "urxvt -e sh -c 'xpathFind ; bash'" },
  { "stacoan",                      "urxvt -e sh -c 'stacoan -h ; bash'" },
  { "jadx",                         "urxvt -e sh -c 'jadx -h ; bash'" },
  { "jadx-gui",                     "urxvt -e sh -c 'jadx-gui ; bash'" },
  { "stoq",                         "urxvt -e sh -c 'stoq -h ; bash'" },
  { "tell-me-your-secrets",         "urxvt -e sh -c 'tell-me-your-secrets -h ; bash'" },
  { "trufflehog",                   "urxvt -e sh -c 'trufflehog -h ; bash'" },
  { "callgrind_annotate",           "urxvt -e sh -c 'callgrind_annotate ; bash'" },
  { "callgrind_control",            "urxvt -e sh -c 'callgrind_control ; bash'" },
  { "cg_annotate",                  "urxvt -e sh -c 'cg_annotate ; bash'" },
  { "cg_diff",                      "urxvt -e sh -c 'cg_diff ; bash'" },
  { "cg_merge",                     "urxvt -e sh -c 'cg_merge ; bash'" },
  { "ms_print",                     "urxvt -e sh -c 'ms_print ; bash'" },
  { "valgrind",                     "urxvt -e sh -c 'valgrind ; bash'" },
  { "valgrind-di-server",           "urxvt -e sh -c 'valgrind-di-server ; bash'" },
  { "valgrind-listener",            "urxvt -e sh -c 'valgrind-listener ; bash'" },
  { "vgdb",                         "urxvt -e sh -c 'vgdb ; bash'" },
  { "callgrind_annotate",           "urxvt -e sh -c 'callgrind_annotate ; bash'" },
  { "callgrind_control",            "urxvt -e sh -c 'callgrind_control ; bash'" },
  { "cg_annotate",                  "urxvt -e sh -c 'cg_annotate ; bash'" },
  { "cg_diff",                      "urxvt -e sh -c 'cg_diff ; bash'" },
  { "cg_merge",                     "urxvt -e sh -c 'cg_merge ; bash'" },
  { "ms_print",                     "urxvt -e sh -c 'ms_print ; bash'" },
  { "valgrind",                     "urxvt -e sh -c 'valgrind ; bash'" },
  { "valgrind-di-server",           "urxvt -e sh -c 'valgrind-di-server ; bash'" },
  { "valgrind-listener",            "urxvt -e sh -c 'valgrind-listener ; bash'" },
  { "vgdb",                         "urxvt -e sh -c 'vgdb ; bash'" },
  { "whispers",                     "urxvt -e sh -c 'whispers -h ; bash'" },
  { "wpbullet",                     "urxvt -e sh -c 'wpbullet -h ; bash'" },
  { "wscript",                      "urxvt -e sh -c 'wscript ; bash'" },
  { "acorn",                        "urxvt -e sh -c 'acorn ; bash'" },
  { "handlebars",                   "urxvt -e sh -c 'handlebars ; bash'" },
  { "he",                           "urxvt -e sh -c 'he ; bash'" },
  { "_mocha",                       "urxvt -e sh -c '_mocha ; bash'" },
  { "mocha",                        "urxvt -e sh -c 'mocha ; bash'" },
  { "uuid",                         "urxvt -e sh -c 'uuid ; bash'" },
  { "which",                        "urxvt -e sh -c 'which ; bash'" },
  { "yasca",                        "urxvt -e sh -c 'yasca ; bash'" },
}

return codeauditmenu
