crackermenu = {
  { "acccheck",                  "urxvt -e sh -c 'acccheck -h ; bash'" },
  { "aesfix",                    "urxvt -e sh -c 'aesfix ; bash'" },
  { "against",                   "urxvt -e sh -c 'against ; bash'" },
  { "androidpincrack",           "urxvt -e sh -c 'androidpincrack -h ; bash'" },
  { "asleap",                    "urxvt -e sh -c 'asleap -h ; bash'" },
  { "auto-eap",                  "urxvt -e sh -c 'auto-eap -h ; bash'" },
  { "balbuzard",                 "urxvt -e sh -c 'balbuzard ; bash'" },
  { "bbcrack",                   "urxvt -e sh -c 'bbcrack ; bash'" },
  { "bbharvest",                 "urxvt -e sh -c 'bbharvest ; bash'" },
  { "bbtrans",                   "urxvt -e sh -c 'bbtrans ; bash'" },
  { "beleth",                    "urxvt -e sh -c 'beleth -h ; bash'" },
  { "pxedump",                   "urxvt -e sh -c 'pxedump -h ; bash'" },
  { "usbdump",                   "urxvt -e sh -c 'usbdump -h ; bash'" },
  { "bkcrack",                   "urxvt -e sh -c 'bkcrack -h ; bash'" },
  { "bkhive",                    "urxvt -e sh -c 'bkhive -h ; bash'" },
  { "blackbox-scanner",          "urxvt -e sh -c 'blackbox-scanner -h ; bash'" },
  { "bob_admin-sse2",            "urxvt -e sh -c 'bob_admin-sse2 -h ; bash'" },
  { "bob_client-sse2",           "urxvt -e sh -c 'bob_client-sse2 -h ; bash'" },
  { "bob_server-sse2",           "urxvt -e sh -c 'bob_server-sse2 -h ; bash'" },
  { "brut3k1t",                  "urxvt -e sh -c 'brut3k1t -h ; bash'" },
  { "brute-force",               "urxvt -e sh -c 'brute-force -h ; bash'" },
  { "bruteforce-luks",           "urxvt -e sh -c 'bruteforce-luks -h ; bash'" },
  { "bruteforce-salted-openssl", "urxvt -e sh -c 'bruteforce-salted-openssl -h ; bash'" },
  { "bruteforce-wallet",         "urxvt -e sh -c 'bruteforce-wallet ; bash'" },
  { "brutemap",                  "urxvt -e sh -c 'brutemap -h ; bash'" },
  { "brutespray",                "urxvt -e sh -c 'brutespray -h ; bash'" },
  { "brutex",                    "urxvt -e sh -c 'brutex ; bash'" },
  { "brutex-masscan",            "urxvt -e sh -c 'brutex-masscan ; bash'" },
  { "bully",                     "urxvt -e sh -c 'bully -h ; bash'" },
  { "byepass",                   "urxvt -e sh -c 'byepass -h ; bash'" },
  { "passtime",                  "urxvt -e sh -c 'passtime -h ; bash'" },
  { "cewl",                      "urxvt -e sh -c 'cewl -h ; bash'" },
  { "cewl-fab",                  "urxvt -e sh -c 'cewl-fab ; bash'" },
  { "chapcrack",                 "urxvt -e sh -c 'chapcrack -h ; bash'" },
  { "checkpwd",                  "urxvt -e sh -c 'checkpwd -h ; bash'" },
  { "checkpwd_nopw",             "urxvt -e sh -c 'checkpwd_nopw ; bash'" },
  { "chntpw",                    "urxvt -e sh -c 'chntpw ; bash'" },
  { "cpnt",                      "urxvt -e sh -c 'cpnt ; bash'" },
  { "reged",                     "urxvt -e sh -c 'reged ; bash'" },
  { "chntpw",                    "urxvt -e sh -c 'chntpw ; bash'" },
  { "cpnt",                      "urxvt -e sh -c 'cpnt ; bash'" },
  { "reged",                     "urxvt -e sh -c 'reged ; bash'" },
  { "cintruder",                 "urxvt -e sh -c 'cintruder -h ; bash'" },
  { "CAT",                       "urxvt -e sh -c 'CAT ; bash'" },
  { "cisco-auditing-tool",       "urxvt -e sh -c 'cisco-auditing-tool ; bash'" },
  { "cisco-ocs",                 "urxvt -e sh -c 'cisco-ocs ; bash'" },
  { "cisco-scanner",             "urxvt -e sh -c 'cisco-scanner -h ; bash'" },
  { "cisco-snmp-enumeration",    "urxvt -e sh -c 'cisco-snmp-enumeration ; bash'" },
  { "c5c",                       "urxvt -e sh -c 'c5c --help ; bash'" },
  { "cisco7crack",               "urxvt -e sh -c 'cisco7crack -h ; bash'" },
  { "cmospwd",                   "urxvt -e sh -c 'cmospwd -h ; bash'" },
  { "compp",                     "urxvt -e sh -c 'compp -h ; bash'" },
  { "cowpatty",                  "urxvt -e sh -c 'cowpatty -h ; bash'" },
  { "genpmk",                    "urxvt -e sh -c 'genpmk -h ; bash'" },
  { "cowpatty",                  "urxvt -e sh -c 'cowpatty -h ; bash'" },
  { "genpmk",                    "urxvt -e sh -c 'genpmk -h ; bash'" },
  { "crackhor",                  "urxvt -e sh -c 'crackhor -h ; bash'" },
  { "crackle",                   "urxvt -e sh -c 'crackle ; bash'" },
  { "crackqcli",                 "urxvt -e sh -c 'crackqcli ; bash'" },
  { "crack-standalone",          "urxvt -e sh -c 'crack-standalone -h ; bash'" },
  { "crackclient",               "urxvt -e sh -c 'crackclient -h ; bash'" },
  { "crackserver",               "urxvt -e sh -c 'crackserver -h ; bash'" },
  { "cachedump",                 "urxvt -e sh -c 'cachedump cd /usr/share/windows/cachedump ; ls ; bash'" },
  { "lsadump",                   "urxvt -e sh -c 'lsadump ; bash'" },
  { "pwdump",                    "urxvt -e sh -c 'pwdump cd /usr/share/windows/pwdump ; ls ; bash'" },
  { "crowbar",                   "urxvt -e sh -c 'crowbar --help ; bash'" },
  { "cryptohazemultiforcer",     "urxvt -e sh -c 'cryptohazemultiforcer ; bash'" },
  { "cupp",                      "urxvt -e sh -c 'cupp ; bash'" },
  { "dbpwaudit",                 "urxvt -e sh -c 'dbpwaudit -h ; bash'" },
  { "delldrac",                  "urxvt -e sh -c 'delldrac -h ; bash'" },
  { "depant",                    "urxvt -e sh -c 'depant ; bash'" },
  { "device-pharmer",            "urxvt -e sh -c 'device-pharmer -h ; bash'" },
  { "domi-owned",                "urxvt -e sh -c 'domi-owned -h ; bash'" },
  { "doozer",                    "urxvt -e sh -c 'doozer ; bash'" },
  { "doozer-monitor",            "urxvt -e sh -c 'doozer-monitor ; bash'" },
  { "doozestop",                 "urxvt -e sh -c 'doozestop ; bash'" },
  { "dpeparser",                 "urxvt -e sh -c 'dpeparser -h ; bash'" },
  { "enabler",                   "urxvt -e sh -c 'enabler ; bash'" },
  { "bin-seeds",                 "urxvt -e sh -c 'bin-seeds ; bash'" },
  { "bruteforce-erldp",          "urxvt -e sh -c 'bruteforce-erldp ; bash'" },
  { "crack-prng",                "urxvt -e sh -c 'crack-prng ; bash'" },
  { "dictionary-erldp",          "urxvt -e sh -c 'dictionary-erldp -h ; bash'" },
  { "erldp-proxy",               "urxvt -e sh -c 'erldp-proxy -h ; bash'" },
  { "shell-erldp",               "urxvt -e sh -c 'shell-erldp -h ; bash'" },
  { "sweep-default-cookie",      "urxvt -e sh -c 'sweep-default-cookie -h ; bash'" },
  { "evilize",                   "urxvt -e sh -c 'evilize -h ; bash'" },
  { "f-scrack",                  "urxvt -e sh -c 'f-scrack ; bash'" },
  { "facebrute",                 "urxvt -e sh -c 'facebrute -h ; bash'" },
  { "fang",                      "urxvt -e sh -c 'fang -h ; bash'" },
  { "fern-wifi-cracker",         "urxvt -e sh -c 'fern-wifi-cracker ; bash'" },
  { "ftp-scanner",               "urxvt -e sh -c 'ftp-scanner -h ; bash'" },
  { "ftp-spider",                "urxvt -e sh -c 'ftp-spider -h ; bash'" },
  { "gpocrack",                  "urxvt -e sh -c 'gpocrack -h ; bash'" },
  { "habu.arp.ping",             "urxvt -e sh -c 'habu.arp.ping ; bash'" },
  { "habu.arp.poison",           "urxvt -e sh -c 'habu.arp.poison ; bash'" },
  { "habu.arp.sniff",            "urxvt -e sh -c 'habu.arp.sniff ; bash'" },
  { "habu.asydns",               "urxvt -e sh -c 'habu.asydns ; bash'" },
  { "habu.b64",                  "urxvt -e sh -c 'habu.b64 ; bash'" },
  { "habu.cert.clone",           "urxvt -e sh -c 'habu.cert.clone ; bash'" },
  { "habu.cert.names",           "urxvt -e sh -c 'habu.cert.names ; bash'" },
  { "habu.crack.luhn",           "urxvt -e sh -c 'habu.crack.luhn ; bash'" },
  { "habu.crack.snmp",           "urxvt -e sh -c 'habu.crack.snmp ; bash'" },
  { "habu.crypto.fernet",        "urxvt -e sh -c 'habu.crypto.fernet ; bash'" },
  { "habu.crypto.gppref",        "urxvt -e sh -c 'habu.crypto.gppref ; bash'" },
  { "habu.crypto.xor",           "urxvt -e sh -c 'habu.crypto.xor ; bash'" },
  { "habu.data.enrich",          "urxvt -e sh -c 'habu.data.enrich ; bash'" },
  { "habu.data.extract.domain",  "urxvt -e sh -c 'habu.data.extract.domain ; bash'" },
  { "habu.data.extract.email",   "urxvt -e sh -c 'habu.data.extract.email ; bash'" },
  { "habu.data.extract.fqdn",    "urxvt -e sh -c 'habu.data.extract.fqdn ; bash'" },
  { "habu.data.extract.ipv4",    "urxvt -e sh -c 'habu.data.extract.ipv4 ; bash'" },
  { "habu.data.filter",          "urxvt -e sh -c 'habu.data.filter ; bash'" },
  { "habu.data.select",          "urxvt -e sh -c 'habu.data.select ; bash'" },
  { "habu.dhcp.discover",        "urxvt -e sh -c 'habu.dhcp.discover ; bash'" },
  { "habu.dhcp.starvation",      "urxvt -e sh -c 'habu.dhcp.starvation ; bash'" },
  { "habu.dns.lookup.forward",   "urxvt -e sh -c 'habu.dns.lookup.forward ; bash'" },
  { "habu.dns.lookup.reverse",   "urxvt -e sh -c 'habu.dns.lookup.reverse ; bash'" },
  { "habu.eicar",                "urxvt -e sh -c 'habu.eicar ; bash'" },
  { "habu.forkbomb",             "urxvt -e sh -c 'habu.forkbomb ; bash'" },
  { "habu.fqdn.finder",          "urxvt -e sh -c 'habu.fqdn.finder ; bash'" },
  { "habu.gateway.find",         "urxvt -e sh -c 'habu.gateway.find ; bash'" },
  { "habu.host",                 "urxvt -e sh -c 'habu.host ; bash'" },
  { "habu.http.headers",         "urxvt -e sh -c 'habu.http.headers ; bash'" },
  { "habu.http.options",         "urxvt -e sh -c 'habu.http.options ; bash'" },
  { "habu.http.tech",            "urxvt -e sh -c 'habu.http.tech ; bash'" },
  { "habu.icmp.ping",            "urxvt -e sh -c 'habu.icmp.ping ; bash'" },
  { "habu.ip.asn",               "urxvt -e sh -c 'habu.ip.asn ; bash'" },
  { "habu.ip.geolocation",       "urxvt -e sh -c 'habu.ip.geolocation ; bash'" },
  { "habu.ip.internal",          "urxvt -e sh -c 'habu.ip.internal ; bash'" },
  { "habu.ip.public",            "urxvt -e sh -c 'habu.ip.public ; bash'" },
  { "habu.karma",                "urxvt -e sh -c 'habu.karma ; bash'" },
  { "habu.karma.bulk",           "urxvt -e sh -c 'habu.karma.bulk ; bash'" },
  { "habu.land",                 "urxvt -e sh -c 'habu.land ; bash'" },
  { "habu.nc",                   "urxvt -e sh -c 'habu.nc ; bash'" },
  { "habu.net.contest",          "urxvt -e sh -c 'habu.net.contest ; bash'" },
  { "habu.net.interfaces",       "urxvt -e sh -c 'habu.net.interfaces ; bash'" },
  { "habu.nmap.excluded",        "urxvt -e sh -c 'habu.nmap.excluded ; bash'" },
  { "habu.nmap.open",            "urxvt -e sh -c 'habu.nmap.open ; bash'" },
  { "habu.nmap.ports",           "urxvt -e sh -c 'habu.nmap.ports ; bash'" },
  { "habu.protoscan",            "urxvt -e sh -c 'habu.protoscan ; bash'" },
  { "habu.server.ftp",           "urxvt -e sh -c 'habu.server.ftp ; bash'" },
  { "habu.tcp.flags",            "urxvt -e sh -c 'habu.tcp.flags ; bash'" },
  { "habu.tcp.isn",              "urxvt -e sh -c 'habu.tcp.isn ; bash'" },
  { "habu.tcp.scan",             "urxvt -e sh -c 'habu.tcp.scan ; bash'" },
  { "habu.tcp.synflood",         "urxvt -e sh -c 'habu.tcp.synflood ; bash'" },
  { "habu.traceroute",           "urxvt -e sh -c 'habu.traceroute ; bash'" },
  { "habu.upgrade",              "urxvt -e sh -c 'habu.upgrade ; bash'" },
  { "habu.usercheck",            "urxvt -e sh -c 'habu.usercheck ; bash'" },
  { "habu.version",              "urxvt -e sh -c 'habu.version ; bash'" },
  { "habu.vhosts",               "urxvt -e sh -c 'habu.vhosts ; bash'" },
  { "habu.virustotal",           "urxvt -e sh -c 'habu.virustotal ; bash'" },
  { "habu.web.report",           "urxvt -e sh -c 'habu.web.report ; bash'" },
  { "habu.whois.domain",         "urxvt -e sh -c 'habu.whois.domain ; bash'" },
  { "habu.whois.ip",             "urxvt -e sh -c 'habu.whois.ip ; bash'" },
  { "hate-crack",                "urxvt -e sh -c 'hate-crack ; bash'" },
  { "hdmi-sniff",                "urxvt -e sh -c 'hdmi-sniff -h ; bash'" },
  { "htpwdscan",                 "urxvt -e sh -c 'htpwdscan -h ; bash'" },
  { "hydra",                     "urxvt -e sh -c 'hydra -h ; bash'" },
  { "pw-inspector",              "urxvt -e sh -c 'pw-inspector -h ; bash'" },
  { "hydra",                     "urxvt -e sh -c 'hydra -h ; bash'" },
  { "pw-inspector",              "urxvt -e sh -c 'pw-inspector -h ; bash'" },
  { "iax-scan-hosts",            "urxvt -e sh -c 'iax-scan-hosts -h ; bash'" },
  { "iax-scan-users",            "urxvt -e sh -c 'iax-scan-users -h ; bash'" },
  { "ibrute",                    "urxvt -e sh -c 'ibrute -h ; bash'" },
  { "icloudbrutter",             "urxvt -e sh -c 'icloudbrutter ; bash'" },
  { "iheartxor",                 "urxvt -e sh -c 'iheartxor ; bash'" },
  { "iisbf",                     "urxvt -e sh -c 'iisbf ; bash'" },
  { "ikecrack-snarf",            "urxvt -e sh -c 'ikecrack-snarf ; bash'" },
  { "ikeforce",                  "urxvt -e sh -c 'ikeforce -h ; bash'" },
  { "inguma",                    "urxvt -e sh -c 'inguma -h ; bash'" },
  { "ingumagui",                 "urxvt -e sh -c 'ingumagui ; bash'" },
  { "interrogate",               "urxvt -e sh -c 'interrogate -h ; bash'" },
  { "ipmipwn",                   "urxvt -e sh -c 'ipmipwn ; bash'" },
  { "iptv-cli",                  "urxvt -e sh -c 'iptv-cli ; bash'" },
  { "iptv-gui",                  "urxvt -e sh -c 'iptv-gui ; bash'" },
  { "jbrute",                    "urxvt -e sh -c 'jbrute --help ; bash'" },
  { "1password2john",            "urxvt -e sh -c '1password2john ; bash'" },
  { "7z2john",                   "urxvt -e sh -c '7z2john ; bash'" },
  { "DPAPImk2john",              "urxvt -e sh -c 'DPAPImk2john ; bash'" },
  { "SIPdump",                   "urxvt -e sh -c 'SIPdump ; bash'" },
  { "adxcsouf2john",             "urxvt -e sh -c 'adxcsouf2john ; bash'" },
  { "aem2john",                  "urxvt -e sh -c 'aem2john ; bash'" },
  { "aix2john",                  "urxvt -e sh -c 'aix2john ; bash'" },
  { "andotp2john",               "urxvt -e sh -c 'andotp2john ; bash'" },
  { "androidbackup2john",        "urxvt -e sh -c 'androidbackup2john ; bash'" },
  { "androidfde2john",           "urxvt -e sh -c 'androidfde2john ; bash'" },
  { "ansible2john",              "urxvt -e sh -c 'ansible2john ; bash'" },
  { "apex2john",                 "urxvt -e sh -c 'apex2john ; bash'" },
  { "aruba2john",                "urxvt -e sh -c 'aruba2john ; bash'" },
  { "axcrypt2john",              "urxvt -e sh -c 'axcrypt2john ; bash'" },
  { "base64conv",                "urxvt -e sh -c 'base64conv ; bash'" },
  { "bestcrypt2john",            "urxvt -e sh -c 'bestcrypt2john ; bash'" },
  { "bitcoin2john",              "urxvt -e sh -c 'bitcoin2john ; bash'" },
  { "bitlocker2john",            "urxvt -e sh -c 'bitlocker2john ; bash'" },
  { "bitwarden2john",            "urxvt -e sh -c 'bitwarden2john ; bash'" },
  { "bks2john",                  "urxvt -e sh -c 'bks2john ; bash'" },
  { "blockchain2john",           "urxvt -e sh -c 'blockchain2john ; bash'" },
  { "calc_stat",                 "urxvt -e sh -c 'calc_stat ; bash'" },
  { "cisco2john",                "urxvt -e sh -c 'cisco2john ; bash'" },
  { "codepage",                  "urxvt -e sh -c 'codepage ; bash'" },
  { "cprepair",                  "urxvt -e sh -c 'cprepair ; bash'" },
  { "cracf2john",                "urxvt -e sh -c 'cracf2john ; bash'" },
  { "diskcryptor2john",          "urxvt -e sh -c 'diskcryptor2john ; bash'" },
  { "dmg2john",                  "urxvt -e sh -c 'dmg2john ; bash'" },
  { "ecryptfs2john",             "urxvt -e sh -c 'ecryptfs2john ; bash'" },
  { "ejabberd2john",             "urxvt -e sh -c 'ejabberd2john ; bash'" },
  { "electrum2john",             "urxvt -e sh -c 'electrum2john ; bash'" },
  { "encfs2john",                "urxvt -e sh -c 'encfs2john ; bash'" },
  { "enpass2john",               "urxvt -e sh -c 'enpass2john ; bash'" },
  { "ethereum2john",             "urxvt -e sh -c 'ethereum2john ; bash'" },
  { "filezilla2john",            "urxvt -e sh -c 'filezilla2john ; bash'" },
  { "fuzz_option",               "urxvt -e sh -c 'fuzz_option ; bash'" },
  { "geli2john",                 "urxvt -e sh -c 'geli2john ; bash'" },
  { "genincstats",               "urxvt -e sh -c 'genincstats ; bash'" },
  { "genmkvpwd",                 "urxvt -e sh -c 'genmkvpwd ; bash'" },
  { "gpg2john",                  "urxvt -e sh -c 'gpg2john ; bash'" },
  { "hccap2john",                "urxvt -e sh -c 'hccap2john ; bash'" },
  { "hccapx2john",               "urxvt -e sh -c 'hccapx2john ; bash'" },
  { "hextoraw",                  "urxvt -e sh -c 'hextoraw ; bash'" },
  { "htdigest2john",             "urxvt -e sh -c 'htdigest2john ; bash'" },
  { "ibmiscanner2john",          "urxvt -e sh -c 'ibmiscanner2john ; bash'" },
  { "ikescan2john",              "urxvt -e sh -c 'ikescan2john ; bash'" },
  { "ios7tojohn",                "urxvt -e sh -c 'ios7tojohn ; bash'" },
  { "itunes_backup2john",        "urxvt -e sh -c 'itunes_backup2john ; bash'" },
  { "iwork2john",                "urxvt -e sh -c 'iwork2john ; bash'" },
  { "john",                      "urxvt -e sh -c 'john ; bash'" },
  { "kdcdump2john",              "urxvt -e sh -c 'kdcdump2john ; bash'" },
  { "keepass2john",              "urxvt -e sh -c 'keepass2john ; bash'" },
  { "keychain2john",             "urxvt -e sh -c 'keychain2john ; bash'" },
  { "keyring2john",              "urxvt -e sh -c 'keyring2john ; bash'" },
  { "keystore2john",             "urxvt -e sh -c 'keystore2john ; bash'" },
  { "known_hosts2john",          "urxvt -e sh -c 'known_hosts2john ; bash'" },
  { "kwallet2john",              "urxvt -e sh -c 'kwallet2john ; bash'" },
  { "lastpass2john",             "urxvt -e sh -c 'lastpass2john ; bash'" },
  { "ldif2john",                 "urxvt -e sh -c 'ldif2john ; bash'" },
  { "leet",                      "urxvt -e sh -c 'leet ; bash'" },
  { "libreoffice2john",          "urxvt -e sh -c 'libreoffice2john ; bash'" },
  { "lion2john",                 "urxvt -e sh -c 'lion2john ; bash'" },
  { "lion2john-alt",             "urxvt -e sh -c 'lion2john-alt ; bash'" },
  { "lotus2john",                "urxvt -e sh -c 'lotus2john ; bash'" },
  { "luks2john",                 "urxvt -e sh -c 'luks2john ; bash'" },
  { "mac2john",                  "urxvt -e sh -c 'mac2john ; bash'" },
  { "mac2john-alt",              "urxvt -e sh -c 'mac2john-alt ; bash'" },
  { "mcafee_epo2john",           "urxvt -e sh -c 'mcafee_epo2john ; bash'" },
  { "mkvcalcproba",              "urxvt -e sh -c 'mkvcalcproba ; bash'" },
  { "monero2john",               "urxvt -e sh -c 'monero2john ; bash'" },
  { "money2john",                "urxvt -e sh -c 'money2john ; bash'" },
  { "mozilla2john",              "urxvt -e sh -c 'mozilla2john ; bash'" },
  { "multibit2john",             "urxvt -e sh -c 'multibit2john ; bash'" },
  { "neo2john",                  "urxvt -e sh -c 'neo2john ; bash'" },
  { "netntlm",                   "urxvt -e sh -c 'netntlm ; bash'" },
  { "netscreen",                 "urxvt -e sh -c 'netscreen ; bash'" },
  { "network2john",              "urxvt -e sh -c 'network2john ; bash'" },
  { "office2john",               "urxvt -e sh -c 'office2john ; bash'" },
  { "openbsd_softraid2john",     "urxvt -e sh -c 'openbsd_softraid2john ; bash'" },
  { "openssl2john",              "urxvt -e sh -c 'openssl2john ; bash'" },
  { "padlock2john",              "urxvt -e sh -c 'padlock2john ; bash'" },
  { "pass_gen",                  "urxvt -e sh -c 'pass_gen ; bash'" },
  { "pcap2john",                 "urxvt -e sh -c 'pcap2john ; bash'" },
  { "pdf2john",                  "urxvt -e sh -c 'pdf2john ; bash'" },
  { "pem2john",                  "urxvt -e sh -c 'pem2john ; bash'" },
  { "pfx2john",                  "urxvt -e sh -c 'pfx2john ; bash'" },
  { "pgpdisk2john",              "urxvt -e sh -c 'pgpdisk2john ; bash'" },
  { "pgpwde2john",               "urxvt -e sh -c 'pgpwde2john ; bash'" },
  { "potcheck",                  "urxvt -e sh -c 'potcheck ; bash'" },
  { "prosody2john",              "urxvt -e sh -c 'prosody2john ; bash'" },
  { "ps_token2john",             "urxvt -e sh -c 'ps_token2john ; bash'" },
  { "pse2john",                  "urxvt -e sh -c 'pse2john ; bash'" },
  { "putty2john",                "urxvt -e sh -c 'putty2john ; bash'" },
  { "pwsafe2john",               "urxvt -e sh -c 'pwsafe2john ; bash'" },
  { "racf2john",                 "urxvt -e sh -c 'racf2john ; bash'" },
  { "radius2john",               "urxvt -e sh -c 'radius2john ; bash'" },
  { "rar2john",                  "urxvt -e sh -c 'rar2john ; bash'" },
  { "raw2dyna",                  "urxvt -e sh -c 'raw2dyna ; bash'" },
  { "rexgen2rules",              "urxvt -e sh -c 'rexgen2rules ; bash'" },
  { "rulestack",                 "urxvt -e sh -c 'rulestack ; bash'" },
  { "sap2john",                  "urxvt -e sh -c 'sap2john ; bash'" },
  { "sha-dump",                  "urxvt -e sh -c 'sha-dump ; bash'" },
  { "sha-test",                  "urxvt -e sh -c 'sha-test ; bash'" },
  { "signal2john",               "urxvt -e sh -c 'signal2john ; bash'" },
  { "sipdump2john",              "urxvt -e sh -c 'sipdump2john ; bash'" },
  { "sspr2john",                 "urxvt -e sh -c 'sspr2john ; bash'" },
  { "staroffice2john",           "urxvt -e sh -c 'staroffice2john ; bash'" },
  { "strip2john",                "urxvt -e sh -c 'strip2john ; bash'" },
  { "telegram2john",             "urxvt -e sh -c 'telegram2john ; bash'" },
  { "tezos2john",                "urxvt -e sh -c 'tezos2john ; bash'" },
  { "truecrypt2john",            "urxvt -e sh -c 'truecrypt2john ; bash'" },
  { "uaf2john",                  "urxvt -e sh -c 'uaf2john ; bash'" },
  { "unafs",                     "urxvt -e sh -c 'unafs ; bash'" },
  { "undrop",                    "urxvt -e sh -c 'undrop ; bash'" },
  { "unique",                    "urxvt -e sh -c 'unique ; bash'" },
  { "unrule",                    "urxvt -e sh -c 'unrule ; bash'" },
  { "vdi2john",                  "urxvt -e sh -c 'vdi2john ; bash'" },
  { "vmx2john",                  "urxvt -e sh -c 'vmx2john ; bash'" },
  { "vncpcap2john",              "urxvt -e sh -c 'vncpcap2john ; bash'" },
  { "wpapcap2john",              "urxvt -e sh -c 'wpapcap2john ; bash'" },
  { "zip2john",                  "urxvt -e sh -c 'zip2john ; bash'" },
  { "1password2john",            "urxvt -e sh -c '1password2john ; bash'" },
  { "7z2john",                   "urxvt -e sh -c '7z2john ; bash'" },
  { "DPAPImk2john",              "urxvt -e sh -c 'DPAPImk2john ; bash'" },
  { "SIPdump",                   "urxvt -e sh -c 'SIPdump ; bash'" },
  { "adxcsouf2john",             "urxvt -e sh -c 'adxcsouf2john ; bash'" },
  { "aem2john",                  "urxvt -e sh -c 'aem2john ; bash'" },
  { "aix2john",                  "urxvt -e sh -c 'aix2john ; bash'" },
  { "andotp2john",               "urxvt -e sh -c 'andotp2john ; bash'" },
  { "androidbackup2john",        "urxvt -e sh -c 'androidbackup2john ; bash'" },
  { "androidfde2john",           "urxvt -e sh -c 'androidfde2john ; bash'" },
  { "ansible2john",              "urxvt -e sh -c 'ansible2john ; bash'" },
  { "apex2john",                 "urxvt -e sh -c 'apex2john ; bash'" },
  { "aruba2john",                "urxvt -e sh -c 'aruba2john ; bash'" },
  { "axcrypt2john",              "urxvt -e sh -c 'axcrypt2john ; bash'" },
  { "base64conv",                "urxvt -e sh -c 'base64conv ; bash'" },
  { "bestcrypt2john",            "urxvt -e sh -c 'bestcrypt2john ; bash'" },
  { "bitcoin2john",              "urxvt -e sh -c 'bitcoin2john ; bash'" },
  { "bitlocker2john",            "urxvt -e sh -c 'bitlocker2john ; bash'" },
  { "bitwarden2john",            "urxvt -e sh -c 'bitwarden2john ; bash'" },
  { "bks2john",                  "urxvt -e sh -c 'bks2john ; bash'" },
  { "blockchain2john",           "urxvt -e sh -c 'blockchain2john ; bash'" },
  { "calc_stat",                 "urxvt -e sh -c 'calc_stat ; bash'" },
  { "cisco2john",                "urxvt -e sh -c 'cisco2john ; bash'" },
  { "codepage",                  "urxvt -e sh -c 'codepage ; bash'" },
  { "cprepair",                  "urxvt -e sh -c 'cprepair ; bash'" },
  { "cracf2john",                "urxvt -e sh -c 'cracf2john ; bash'" },
  { "diskcryptor2john",          "urxvt -e sh -c 'diskcryptor2john ; bash'" },
  { "dmg2john",                  "urxvt -e sh -c 'dmg2john ; bash'" },
  { "ecryptfs2john",             "urxvt -e sh -c 'ecryptfs2john ; bash'" },
  { "ejabberd2john",             "urxvt -e sh -c 'ejabberd2john ; bash'" },
  { "electrum2john",             "urxvt -e sh -c 'electrum2john ; bash'" },
  { "encfs2john",                "urxvt -e sh -c 'encfs2john ; bash'" },
  { "enpass2john",               "urxvt -e sh -c 'enpass2john ; bash'" },
  { "ethereum2john",             "urxvt -e sh -c 'ethereum2john ; bash'" },
  { "filezilla2john",            "urxvt -e sh -c 'filezilla2john ; bash'" },
  { "fuzz_option",               "urxvt -e sh -c 'fuzz_option ; bash'" },
  { "geli2john",                 "urxvt -e sh -c 'geli2john ; bash'" },
  { "genincstats",               "urxvt -e sh -c 'genincstats ; bash'" },
  { "genmkvpwd",                 "urxvt -e sh -c 'genmkvpwd ; bash'" },
  { "gpg2john",                  "urxvt -e sh -c 'gpg2john ; bash'" },
  { "hccap2john",                "urxvt -e sh -c 'hccap2john ; bash'" },
  { "hccapx2john",               "urxvt -e sh -c 'hccapx2john ; bash'" },
  { "hextoraw",                  "urxvt -e sh -c 'hextoraw ; bash'" },
  { "htdigest2john",             "urxvt -e sh -c 'htdigest2john ; bash'" },
  { "ibmiscanner2john",          "urxvt -e sh -c 'ibmiscanner2john ; bash'" },
  { "ikescan2john",              "urxvt -e sh -c 'ikescan2john ; bash'" },
  { "ios7tojohn",                "urxvt -e sh -c 'ios7tojohn ; bash'" },
  { "itunes_backup2john",        "urxvt -e sh -c 'itunes_backup2john ; bash'" },
  { "iwork2john",                "urxvt -e sh -c 'iwork2john ; bash'" },
  { "john",                      "urxvt -e sh -c 'john ; bash'" },
  { "kdcdump2john",              "urxvt -e sh -c 'kdcdump2john ; bash'" },
  { "keepass2john",              "urxvt -e sh -c 'keepass2john ; bash'" },
  { "keychain2john",             "urxvt -e sh -c 'keychain2john ; bash'" },
  { "keyring2john",              "urxvt -e sh -c 'keyring2john ; bash'" },
  { "keystore2john",             "urxvt -e sh -c 'keystore2john ; bash'" },
  { "known_hosts2john",          "urxvt -e sh -c 'known_hosts2john ; bash'" },
  { "kwallet2john",              "urxvt -e sh -c 'kwallet2john ; bash'" },
  { "lastpass2john",             "urxvt -e sh -c 'lastpass2john ; bash'" },
  { "ldif2john",                 "urxvt -e sh -c 'ldif2john ; bash'" },
  { "leet",                      "urxvt -e sh -c 'leet ; bash'" },
  { "libreoffice2john",          "urxvt -e sh -c 'libreoffice2john ; bash'" },
  { "lion2john",                 "urxvt -e sh -c 'lion2john ; bash'" },
  { "lion2john-alt",             "urxvt -e sh -c 'lion2john-alt ; bash'" },
  { "lotus2john",                "urxvt -e sh -c 'lotus2john ; bash'" },
  { "luks2john",                 "urxvt -e sh -c 'luks2john ; bash'" },
  { "mac2john",                  "urxvt -e sh -c 'mac2john ; bash'" },
  { "mac2john-alt",              "urxvt -e sh -c 'mac2john-alt ; bash'" },
  { "mcafee_epo2john",           "urxvt -e sh -c 'mcafee_epo2john ; bash'" },
  { "mkvcalcproba",              "urxvt -e sh -c 'mkvcalcproba ; bash'" },
  { "monero2john",               "urxvt -e sh -c 'monero2john ; bash'" },
  { "money2john",                "urxvt -e sh -c 'money2john ; bash'" },
  { "mozilla2john",              "urxvt -e sh -c 'mozilla2john ; bash'" },
  { "multibit2john",             "urxvt -e sh -c 'multibit2john ; bash'" },
  { "neo2john",                  "urxvt -e sh -c 'neo2john ; bash'" },
  { "netntlm",                   "urxvt -e sh -c 'netntlm ; bash'" },
  { "netscreen",                 "urxvt -e sh -c 'netscreen ; bash'" },
  { "network2john",              "urxvt -e sh -c 'network2john ; bash'" },
  { "office2john",               "urxvt -e sh -c 'office2john ; bash'" },
  { "openbsd_softraid2john",     "urxvt -e sh -c 'openbsd_softraid2john ; bash'" },
  { "openssl2john",              "urxvt -e sh -c 'openssl2john ; bash'" },
  { "padlock2john",              "urxvt -e sh -c 'padlock2john ; bash'" },
  { "pass_gen",                  "urxvt -e sh -c 'pass_gen ; bash'" },
  { "pcap2john",                 "urxvt -e sh -c 'pcap2john ; bash'" },
  { "pdf2john",                  "urxvt -e sh -c 'pdf2john ; bash'" },
  { "pem2john",                  "urxvt -e sh -c 'pem2john ; bash'" },
  { "pfx2john",                  "urxvt -e sh -c 'pfx2john ; bash'" },
  { "pgpdisk2john",              "urxvt -e sh -c 'pgpdisk2john ; bash'" },
  { "pgpwde2john",               "urxvt -e sh -c 'pgpwde2john ; bash'" },
  { "potcheck",                  "urxvt -e sh -c 'potcheck ; bash'" },
  { "prosody2john",              "urxvt -e sh -c 'prosody2john ; bash'" },
  { "ps_token2john",             "urxvt -e sh -c 'ps_token2john ; bash'" },
  { "pse2john",                  "urxvt -e sh -c 'pse2john ; bash'" },
  { "putty2john",                "urxvt -e sh -c 'putty2john ; bash'" },
  { "pwsafe2john",               "urxvt -e sh -c 'pwsafe2john ; bash'" },
  { "racf2john",                 "urxvt -e sh -c 'racf2john ; bash'" },
  { "radius2john",               "urxvt -e sh -c 'radius2john ; bash'" },
  { "rar2john",                  "urxvt -e sh -c 'rar2john ; bash'" },
  { "raw2dyna",                  "urxvt -e sh -c 'raw2dyna ; bash'" },
  { "rexgen2rules",              "urxvt -e sh -c 'rexgen2rules ; bash'" },
  { "rulestack",                 "urxvt -e sh -c 'rulestack ; bash'" },
  { "sap2john",                  "urxvt -e sh -c 'sap2john ; bash'" },
  { "sha-dump",                  "urxvt -e sh -c 'sha-dump ; bash'" },
  { "sha-test",                  "urxvt -e sh -c 'sha-test ; bash'" },
  { "signal2john",               "urxvt -e sh -c 'signal2john ; bash'" },
  { "sipdump2john",              "urxvt -e sh -c 'sipdump2john ; bash'" },
  { "sspr2john",                 "urxvt -e sh -c 'sspr2john ; bash'" },
  { "staroffice2john",           "urxvt -e sh -c 'staroffice2john ; bash'" },
  { "strip2john",                "urxvt -e sh -c 'strip2john ; bash'" },
  { "telegram2john",             "urxvt -e sh -c 'telegram2john ; bash'" },
  { "tezos2john",                "urxvt -e sh -c 'tezos2john ; bash'" },
  { "truecrypt2john",            "urxvt -e sh -c 'truecrypt2john ; bash'" },
  { "uaf2john",                  "urxvt -e sh -c 'uaf2john ; bash'" },
  { "unafs",                     "urxvt -e sh -c 'unafs ; bash'" },
  { "undrop",                    "urxvt -e sh -c 'undrop ; bash'" },
  { "unique",                    "urxvt -e sh -c 'unique ; bash'" },
  { "unrule",                    "urxvt -e sh -c 'unrule ; bash'" },
  { "vdi2john",                  "urxvt -e sh -c 'vdi2john ; bash'" },
  { "vmx2john",                  "urxvt -e sh -c 'vmx2john ; bash'" },
  { "vncpcap2john",              "urxvt -e sh -c 'vncpcap2john ; bash'" },
  { "wpapcap2john",              "urxvt -e sh -c 'wpapcap2john ; bash'" },
  { "zip2john",                  "urxvt -e sh -c 'zip2john ; bash'" },
  { "johnny",                    "urxvt -e sh -c 'johnny ; bash'" },
  { "jooforce",                  "urxvt -e sh -c 'jooforce ; bash'" },
  { "jwt-cracker",               "urxvt -e sh -c 'jwt-cracker ; bash'" },
  { "jwt-tool",                  "urxvt -e sh -c 'jwt-tool -h ; bash'" },
  { "jwtcat",                    "urxvt -e sh -c 'jwtcat -h ; bash'" },
  { "katana-ktf.gui",            "urxvt -e sh -c 'katana-ktf.gui ; bash'" },
  { "katana-ktfconsole",         "urxvt -e sh -c 'katana-ktfconsole ; bash'" },
  { "katana-ktfktf",             "urxvt -e sh -c 'katana-ktfktf ; bash'" },
  { "katana-ktflinker",          "urxvt -e sh -c 'katana-ktflinker ; bash'" },
  { "katana-ktfrun",             "urxvt -e sh -c 'katana-ktfrun ; bash'" },
  { "katana-ktfupdate",          "urxvt -e sh -c 'katana-ktfupdate ; bash'" },
  { "keimpx",                    "urxvt -e sh -c 'keimpx -h ; bash'" },
  { "khc",                       "urxvt -e sh -c 'khc ; bash'" },
  { "ldap-brute",                "urxvt -e sh -c 'ldap-brute -h ; bash'" },
  { "leviathan",                 "urxvt -e sh -c 'leviathan ; bash'" },
  { "levye",                     "urxvt -e sh -c 'levye -h ; bash'" },
  { "linset",                    "urxvt -e sh -c 'linset ; bash'" },
  { "lodowep",                   "urxvt -e sh -c 'lodowep -h ; bash'" },
  { "lyricpass",                 "urxvt -e sh -c 'lyricpass -h ; bash'" },
  { "mdcrack",                   "urxvt -e sh -c 'mdcrack ; bash'" },
  { "medusa",                    "urxvt -e sh -c 'medusa -h ; bash'" },
  { "mentalist",                 "urxvt -e sh -c 'mentalist ; bash'" },
  { "mfoc",                      "urxvt -e sh -c 'mfoc -h ; bash'" },
  { "mimipenguin",               "urxvt -e sh -c 'mimipenguin ; bash'" },
  { "mkbrutus",                  "urxvt -e sh -c 'mkbrutus -h ; bash'" },
  { "morxbook",                  "urxvt -e sh -c 'morxbook ; bash'" },
  { "morxbrute",                 "urxvt -e sh -c 'morxbrute ; bash'" },
  { "morxbtcrack",               "urxvt -e sh -c 'morxbtcrack ; bash'" },
  { "morxcoinpwn",               "urxvt -e sh -c 'morxcoinpwn ; bash'" },
  { "morxcrack",                 "urxvt -e sh -c 'morxcrack -h ; bash'" },
  { "mybff",                     "urxvt -e sh -c 'mybff -h ; bash'" },
  { "myjwt",                     "urxvt -e sh -c 'myjwt -h ; bash'" },
  { "ncrack",                    "urxvt -e sh -c 'ncrack -h ; bash'" },
  { "o365spray",                 "urxvt -e sh -c 'o365spray -h ; bash'" },
  { "obevilion",                 "urxvt -e sh -c 'obevilion --help ; bash'" },
  { "ocs-cisco",                 "urxvt -e sh -c 'ocs-cisco ; bash'" },
  { "omen-alphabetcreator",      "urxvt -e sh -c 'omen-alphabetcreator -h ; bash'" },
  { "omen-createng",             "urxvt -e sh -c 'omen-createng -h ; bash'" },
  { "omen-enumng",               "urxvt -e sh -c 'omen-enumng -h ; bash'" },
  { "omen-evalpw",               "urxvt -e sh -c 'omen-evalpw -h ; bash'" },
  { "onesixtyone",               "urxvt -e sh -c 'onesixtyone ; bash'" },
  { "ophcrack",                  "urxvt -e sh -c 'ophcrack -h ; bash'" },
  { "owabf",                     "urxvt -e sh -c 'owabf -h ; bash'" },
  { "maskgen",                   "urxvt -e sh -c 'maskgen -h ; bash'" },
  { "policygen",                 "urxvt -e sh -c 'policygen -h ; bash'" },
  { "rulegen",                   "urxvt -e sh -c 'rulegen -h ; bash'" },
  { "statsgen",                  "urxvt -e sh -c 'statsgen -h ; bash'" },
  { "passcracking",              "urxvt -e sh -c 'passcracking ; bash'" },
  { "passe-partout",             "urxvt -e sh -c 'passe-partout -h ; bash'" },
  { "patator",                   "urxvt -e sh -c 'patator --help ; bash'" },
  { "pdfcrack",                  "urxvt -e sh -c 'pdfcrack ; bash'" },
  { "pdgmail",                   "urxvt -e sh -c 'pdgmail -h ; bash'" },
  { "pemcrack",                  "urxvt -e sh -c 'pemcrack ; bash'" },
  { "pemcracker",                "urxvt -e sh -c 'pemcracker ; bash'" },
  { "PHoss",                     "urxvt -e sh -c 'PHoss -h ; bash'" },
  { "php-mt-seed",               "urxvt -e sh -c 'php-mt-seed ; bash'" },
  { "phrasendrescher",           "urxvt -e sh -c 'phrasendrescher -h ; bash'" },
  { "pipal",                     "urxvt -e sh -c 'pipal ; bash'" },
  { "pipeline",                  "urxvt -e sh -c 'pipeline ; bash'" },
  { "pkcrack",                   "urxvt -e sh -c 'pkcrack ; bash'" },
  { "pkcrack-extract",           "urxvt -e sh -c 'pkcrack-extract ; bash'" },
  { "pwcrack",                   "urxvt -e sh -c 'pwcrack -h ; bash'" },
  { "pybozocrack",               "urxvt -e sh -c 'pybozocrack -h ; bash'" },
  { "pyrit",                     "urxvt -e sh -c 'pyrit -h ; bash'" },
  { "pythem",                    "urxvt -e sh -c 'pythem ; bash'" },
  { "rcrack",                    "urxvt -e sh -c 'rcrack ; bash'" },
  { "rt2rtc",                    "urxvt -e sh -c 'rt2rtc ; bash'" },
  { "rtc2rt",                    "urxvt -e sh -c 'rtc2rt ; bash'" },
  { "rtgen",                     "urxvt -e sh -c 'rtgen ; bash'" },
  { "rtmerge",                   "urxvt -e sh -c 'rtmerge ; bash'" },
  { "rtsort",                    "urxvt -e sh -c 'rtsort ; bash'" },
  { "rarcrack",                  "urxvt -e sh -c 'rarcrack --help ; bash'" },
  { "rcracki_mt",                "urxvt -e sh -c 'rcracki_mt ; bash'" },
  { "rdesktop-brute",            "urxvt -e sh -c 'rdesktop-brute -h ; bash'" },
  { "rdpassspray",               "urxvt -e sh -c 'rdpassspray -h ; bash'" },
  { "reaver",                    "urxvt -e sh -c 'reaver ; bash'" },
  { "rhodiola",                  "urxvt -e sh -c 'rhodiola -h ; bash'" },
  { "ridenum",                   "urxvt -e sh -c 'ridenum -h ; bash'" },
  { "rlogin-scanner",            "urxvt -e sh -c 'rlogin-scanner -h ; bash'" },
  { "rootbrute",                 "urxvt -e sh -c 'rootbrute -h ; bash'" },
  { "rpdscan",                   "urxvt -e sh -c 'rpdscan -h ; bash'" },
  { "rsactftool",                "urxvt -e sh -c 'rsactftool -h ; bash'" },
  { "samydeluxe",                "urxvt -e sh -c 'samydeluxe -h ; bash'" },
  { "sb0x",                      "urxvt -e sh -c 'sb0x -h ; bash'" },
  { "shreder",                   "urxvt -e sh -c 'shreder -h ; bash'" },
  { "sidguess",                  "urxvt -e sh -c 'sidguess ; bash'" },
  { "sipbrute",                  "urxvt -e sh -c 'sipbrute -h ; bash'" },
  { "sipcrack",                  "urxvt -e sh -c 'sipcrack -h ; bash'" },
  { "sipdump",                   "urxvt -e sh -c 'sipdump -h ; bash'" },
  { "skul",                      "urxvt -e sh -c 'skul ; bash'" },
  { "nbdecode",                  "urxvt -e sh -c 'nbdecode ; bash'" },
  { "smbbf",                     "urxvt -e sh -c 'smbbf -h ; bash'" },
  { "smbdumpusers",              "urxvt -e sh -c 'smbdumpusers ; bash'" },
  { "smbgetserverinfo",          "urxvt -e sh -c 'smbgetserverinfo ; bash'" },
  { "smtptester",                "urxvt -e sh -c 'smtptester -h ; bash'" },
  { "sn1per",                    "urxvt -e sh -c 'sn1per ; bash'" },
  { "http-default-accounts-fingerprints-nndefaccts.lua",
    "urxvt -e sh -c 'http-default-accounts-fingerprints-nndefaccts.lua ; bash'" },
  { "inurlbr.php",        "urxvt -e sh -c 'inurlbr.php ; bash'" },
  { "nmap-bootstrap.xsl", "urxvt -e sh -c 'nmap-bootstrap.xsl ; bash'" },
  { "snmpbrute",          "urxvt -e sh -c 'snmpbrute ; bash'" },
  { "sparta",             "urxvt -e sh -c 'sparta ; bash'" },
  { "speedport-arcadyan", "urxvt -e sh -c 'speedport-arcadyan ; bash'" },
  { "speedpwn",           "urxvt -e sh -c 'speedpwn -h ; bash'" },
  { "sqlbf",              "urxvt -e sh -c 'sqlbf ; bash'" },
  { "sslnuke",            "urxvt -e sh -c 'sslnuke ; bash'" },
  { "sucrack",            "urxvt -e sh -c 'sucrack ; bash'" },
  { "swarm",              "urxvt -e sh -c 'swarm -h ; bash'" },
  { "tftpbrute",          "urxvt -e sh -c 'tftpbrute ; bash'" },
  { "keyfinder",          "urxvt -e sh -c 'keyfinder ; bash'" },
  { "thc-pptp-bruter",    "urxvt -e sh -c 'thc-pptp-bruter ; bash'" },
  { "thc-smartbrute",     "urxvt -e sh -c 'thc-smartbrute -h ; bash'" },
  { "ttpassgen",          "urxvt -e sh -c 'ttpassgen -h ; bash'" },
  { "ufo-wardriving",     "urxvt -e sh -c 'ufo-wardriving ; bash'" },
  { "vnc-bypauth",        "urxvt -e sh -c 'vnc-bypauth ; bash'" },
  { "vncrack",            "urxvt -e sh -c 'vncrack ; bash'" },
  { "wifibroot",          "urxvt -e sh -c 'wifibroot -h ; bash'" },
  { "wifite",             "urxvt -e sh -c 'wifite ; bash'" },
  { "wmat",               "urxvt -e sh -c 'wmat ; bash'" },
  { "wordbrutepress",     "urxvt -e sh -c 'wordbrutepress ; bash'" },
  { "wpbf",               "urxvt -e sh -c 'wpbf -h ; bash'" },
  { "wpbrute-rpc",        "urxvt -e sh -c 'wpbrute-rpc ; bash'" },
  { "wpforce",            "urxvt -e sh -c 'wpforce -h ; bash'" },
  { "wpforce-yertle",     "urxvt -e sh -c 'wpforce-yertle -h ; bash'" },
  { "wyd",                "urxvt -e sh -c 'wyd ; bash'" },
  { "zackattack",         "urxvt -e sh -c 'zackattack -h ; bash'" },
  { "zulu",               "urxvt -e sh -c 'zulu ; bash'" },
}

return crackermenu
