cryptomenu = {
  { "aespipe",                    "urxvt -e sh -c 'aespipe -h ; bash'" },
  { "argon2",                     "urxvt -e sh -c 'argon2 -h ; bash'" },
  { "armor",                      "urxvt -e sh -c 'armor ; bash'" },
  { "athena-ssl-scanner",         "urxvt -e sh -c 'athena-ssl-scanner -h ; bash'" },
  { "auto-xor-decryptor",         "urxvt -e sh -c 'auto-xor-decryptor ; bash'" },
  { "bletchley-analyze",          "urxvt -e sh -c 'bletchley-analyze ; bash'" },
  { "bletchley-clonecertchain",   "urxvt -e sh -c 'bletchley-clonecertchain ; bash'" },
  { "bletchley-decode",           "urxvt -e sh -c 'bletchley-decode ; bash'" },
  { "bletchley-encode",           "urxvt -e sh -c 'bletchley-encode ; bash'" },
  { "bletchley-nextrand",         "urxvt -e sh -c 'bletchley-nextrand ; bash'" },
  { "bruteforce-luks",            "urxvt -e sh -c 'bruteforce-luks -h ; bash'" },
  { "bruteforce-salted-openssl",  "urxvt -e sh -c 'bruteforce-salted-openssl -h ; bash'" },
  { "bruteforce-wallet",          "urxvt -e sh -c 'bruteforce-wallet ; bash'" },
  { "cipherscan",                 "urxvt -e sh -c 'cipherscan ; bash'" },
  { "ciphertest",                 "urxvt -e sh -c 'ciphertest ; bash'" },
  { "ciphr",                      "urxvt -e sh -c 'ciphr -h ; bash'" },
  { "c5c",                        "urxvt -e sh -c 'c5c --help ; bash'" },
  { "cisco7crack",                "urxvt -e sh -c 'cisco7crack -h ; bash'" },
  { "cloakify",                   "urxvt -e sh -c 'cloakify ; bash'" },
  { "decloakify",                 "urxvt -e sh -c 'decloakify ; bash'" },
  { "codetective",                "urxvt -e sh -c 'codetective -h ; bash'" },
  { "cribdrag",                   "urxvt -e sh -c 'cribdrag -h ; bash'" },
  { "cribdrag-xorstrings",        "urxvt -e sh -c 'cribdrag-xorstrings -h ; bash'" },
  { "cryptohazemultiforcer",      "urxvt -e sh -c 'cryptohazemultiforcer ; bash'" },
  { "cnark",                      "urxvt -e sh -c 'cnark ; bash'" },
  { "dagon",                      "urxvt -e sh -c 'dagon -h ; bash'" },
  { "daredevil",                  "urxvt -e sh -c 'daredevil -h ; bash'" },
  { "decodify",                   "urxvt -e sh -c 'decodify -h ; bash'" },
  { "deen",                       "urxvt -e sh -c 'deen ; bash'" },
  { "demiguise",                  "urxvt -e sh -c 'demiguise -h ; bash'" },
  { "dislocker",                  "urxvt -e sh -c 'dislocker -h ; bash'" },
  { "dislocker-bek",              "urxvt -e sh -c 'dislocker-bek ; bash'" },
  { "dislocker-file",             "urxvt -e sh -c 'dislocker-file ; bash'" },
  { "dislocker-find",             "urxvt -e sh -c 'dislocker-find ; bash'" },
  { "dislocker-fuse",             "urxvt -e sh -c 'dislocker-fuse ; bash'" },
  { "dislocker-metadata",         "urxvt -e sh -c 'dislocker-metadata ; bash'" },
  { "bunnyducky",                 "urxvt -e sh -c 'bunnyducky -h ; bash'" },
  { "ducktools",                  "urxvt -e sh -c 'ducktools -h ; bash'" },
  { "evilize",                    "urxvt -e sh -c 'evilize -h ; bash'" },
  { "factordb",                   "urxvt -e sh -c 'factordb -h ; bash'" },
  { "featherduster",              "urxvt -e sh -c 'featherduster -h ; bash'" },
  { "foresee",                    "urxvt -e sh -c 'foresee -h ; bash'" },
  { "gcrypt",                     "urxvt -e sh -c 'gcrypt --help ; bash'" },
  { "haiti",                      "urxvt -e sh -c 'haiti -h ; bash'" },
  { "haiti_console",              "urxvt -e sh -c 'haiti_console ; bash'" },
  { "md5deep",                    "urxvt -e sh -c 'md5deep -h ; bash'" },
  { "sha1deep",                   "urxvt -e sh -c 'sha1deep -h ; bash'" },
  { "sha256deep",                 "urxvt -e sh -c 'sha256deep -h ; bash'" },
  { "tigerdeep",                  "urxvt -e sh -c 'tigerdeep -h ; bash'" },
  { "whirlpooldeep",              "urxvt -e sh -c 'whirlpooldeep -h ; bash'" },
  { "md5deep",                    "urxvt -e sh -c 'md5deep -h ; bash'" },
  { "sha1deep",                   "urxvt -e sh -c 'sha1deep -h ; bash'" },
  { "sha256deep",                 "urxvt -e sh -c 'sha256deep -h ; bash'" },
  { "tigerdeep",                  "urxvt -e sh -c 'tigerdeep -h ; bash'" },
  { "whirlpooldeep",              "urxvt -e sh -c 'whirlpooldeep -h ; bash'" },
  { "wlangenpmk",                 "urxvt -e sh -c 'wlangenpmk -h ; bash'" },
  { "wlangenpmkocl",              "urxvt -e sh -c 'wlangenpmkocl -h ; bash'" },
  { "wlangenpmk",                 "urxvt -e sh -c 'wlangenpmk -h ; bash'" },
  { "wlangenpmkocl",              "urxvt -e sh -c 'wlangenpmkocl -h ; bash'" },
  { "ja3",                        "urxvt -e sh -c 'ja3 -h ; bash'" },
  { "kraken",                     "urxvt -e sh -c 'kraken -h ; bash'" },
  { "bdeinfo",                    "urxvt -e sh -c 'bdeinfo ; bash'" },
  { "bdemount",                   "urxvt -e sh -c 'bdemount ; bash'" },
  { "lbb.db",                     "urxvt -e sh -c 'lbb.db ; bash'" },
  { "littleblackbox",             "urxvt -e sh -c 'littleblackbox -h ; bash'" },
  { "luksipc",                    "urxvt -e sh -c 'luksipc -h ; bash'" },
  { "morxcrack",                  "urxvt -e sh -c 'morxcrack -h ; bash'" },
  { "nomorexor",                  "urxvt -e sh -c 'nomorexor ; bash'" },
  { "omen-alphabetcreator",       "urxvt -e sh -c 'omen-alphabetcreator -h ; bash'" },
  { "omen-createng",              "urxvt -e sh -c 'omen-createng -h ; bash'" },
  { "omen-enumng",                "urxvt -e sh -c 'omen-enumng -h ; bash'" },
  { "omen-evalpw",                "urxvt -e sh -c 'omen-evalpw -h ; bash'" },
  { "openstego",                  "urxvt -e sh -c 'openstego -h ; bash'" },
  { "outguess",                   "urxvt -e sh -c 'outguess ; bash'" },
  { "pip3line",                   "urxvt -e sh -c 'pip3line ; bash'" },
  { "posttester",                 "urxvt -e sh -c 'posttester -h ; bash'" },
  { "pwdlyser",                   "urxvt -e sh -c 'pwdlyser -h ; bash'" },
  { "pybozocrack",                "urxvt -e sh -c 'pybozocrack -h ; bash'" },
  { "pyssltest",                  "urxvt -e sh -c 'pyssltest -h ; bash'" },
  { "rdp-cipher-checker",         "urxvt -e sh -c 'rdp-cipher-checker ; bash'" },
  { "rsactftool",                 "urxvt -e sh -c 'rsactftool -h ; bash'" },
  { "rsatool",                    "urxvt -e sh -c 'rsatool -h ; bash'" },
  { "rupture",                    "urxvt -e sh -c 'rupture -h ; bash'" },
  { "sandy",                      "urxvt -e sh -c 'sandy -h ; bash'" },
  { "sbd",                        "urxvt -e sh -c 'sbd -h ; bash'" },
  { "sha1dcsum",                  "urxvt -e sh -c 'sha1dcsum ; bash'" },
  { "sha1dcsum_partialcoll",      "urxvt -e sh -c 'sha1dcsum_partialcoll ; bash'" },
  { "sherlocked",                 "urxvt -e sh -c 'sherlocked ; bash'" },
  { "stripx",                     "urxvt -e sh -c 'stripx ; bash'" },
  { "stub",                       "urxvt -e sh -c 'stub ; bash'" },
  { "skul",                       "urxvt -e sh -c 'skul ; bash'" },
  { "snapception",                "urxvt -e sh -c 'snapception --help ; bash'" },
  { "snow",                       "urxvt -e sh -c 'snow -h ; bash'" },
  { "spipe",                      "urxvt -e sh -c 'spipe ; bash'" },
  { "spiped",                     "urxvt -e sh -c 'spiped ; bash'" },
  { "ssdeep",                     "urxvt -e sh -c 'ssdeep ; bash'" },
  { "sslcaudit",                  "urxvt -e sh -c 'sslcaudit -h ; bash'" },
  { "ssllabs-scan",               "urxvt -e sh -c 'ssllabs-scan -h ; bash'" },
  { "sslmap",                     "urxvt -e sh -c 'sslmap -h ; bash'" },
  { "sslscan",                    "urxvt -e sh -c 'sslscan ; bash'" },
  { "sslyze",                     "urxvt -e sh -c 'sslyze -h ; bash'" },
  { "tchunt-ng",                  "urxvt -e sh -c 'tchunt-ng -h ; bash'" },
  { "testssl",                    "urxvt -e sh -c 'testssl ; bash'" },
  { "tls-attacker-Attacks",       "urxvt -e sh -c 'tls-attacker-Attacks ; bash'" },
  { "tls-attacker-TLS-Client",    "urxvt -e sh -c 'tls-attacker-TLS-Client ; bash'" },
  { "tls-attacker-TLS-Forensics", "urxvt -e sh -c 'tls-attacker-TLS-Forensics ; bash'" },
  { "tls-attacker-TLS-Mitm",      "urxvt -e sh -c 'tls-attacker-TLS-Mitm ; bash'" },
  { "tls-attacker-TLS-Server",    "urxvt -e sh -c 'tls-attacker-TLS-Server ; bash'" },
  { "tls-attacker-TraceTool",     "urxvt -e sh -c 'tls-attacker-TraceTool ; bash'" },
  { "tls-map",                    "urxvt -e sh -c 'tls-map -h ; bash'" },
  { "tls-prober",                 "urxvt -e sh -c 'tls-prober -h ; bash'" },
  { "tlsenum",                    "urxvt -e sh -c 'tlsenum -h ; bash'" },
  { "tlspretense",                "urxvt -e sh -c 'tlspretense ; bash'" },
  { "untwister",                  "urxvt -e sh -c 'untwister -h ; bash'" },
  { "veracrypt",                  "urxvt -e sh -c 'veracrypt ; bash'" },
  { "webfixy",                    "urxvt -e sh -c 'webfixy -h ; bash'" },
  { "x-rsa",                      "urxvt -e sh -c 'x-rsa -h ; bash'" },
  { "xorsearch",                  "urxvt -e sh -c 'xorsearch ; bash'" },
  { "xortool",                    "urxvt -e sh -c 'xortool -h ; bash'" },
  { "xortool-xor",                "urxvt -e sh -c 'xortool-xor ; bash'" },
  { "xortool",                    "urxvt -e sh -c 'xortool -h ; bash'" },
  { "xortool-xor",                "urxvt -e sh -c 'xortool-xor ; bash'" },
  { "zuluCrypt-cli",              "urxvt -e sh -c 'zuluCrypt-cli -h ; bash'" },
  { "zuluCrypt-gui",              "urxvt -e sh -c 'zuluCrypt-gui ; bash'" },
  { "zuluMount-cli",              "urxvt -e sh -c 'zuluMount-cli -h ; bash'" },
  { "zuluMount-gui",              "urxvt -e sh -c 'zuluMount-gui ; bash'" },
  { "zuluPolkit",                 "urxvt -e sh -c 'zuluPolkit -h ; bash'" },
  { "zuluSafe-cli",               "urxvt -e sh -c 'zuluSafe-cli -h ; bash'" },
}

return cryptomenu
