debuggermenu = {
  { "bindead",                "urxvt -e sh -c 'bindead ; bash'" },
  { "binflow",                "urxvt -e sh -c 'binflow ; bash'" },
  { "dwarf",                  "urxvt -e sh -c 'dwarf --help ; bash'" },
  { "edb",                    "urxvt -e sh -c 'edb ; bash'" },
  { "electric-fence",         "urxvt -e sh -c 'electric-fence ; bash'" },
  { "e2dbg32",                "urxvt -e sh -c 'e2dbg32 ; bash'" },
  { "e2dbg64",                "urxvt -e sh -c 'e2dbg64 ; bash'" },
  { "etrace32",               "urxvt -e sh -c 'etrace32 ; bash'" },
  { "etrace64",               "urxvt -e sh -c 'etrace64 ; bash'" },
  { "evarista32",             "urxvt -e sh -c 'evarista32 ; bash'" },
  { "evarista64",             "urxvt -e sh -c 'evarista64 ; bash'" },
  { "kedbg32",                "urxvt -e sh -c 'kedbg32 ; bash'" },
  { "kedbg64",                "urxvt -e sh -c 'kedbg64 ; bash'" },
  { "gcore",                  "urxvt -e sh -c 'gcore ; bash'" },
  { "gdb",                    "urxvt -e sh -c 'gdb -h ; bash'" },
  { "gdbserver",              "urxvt -e sh -c 'gdbserver --help ; bash'" },
  { "gcore",                  "urxvt -e sh -c 'gcore ; bash'" },
  { "gdb",                    "urxvt -e sh -c 'gdb -h ; bash'" },
  { "gdbserver",              "urxvt -e sh -c 'gdbserver --help ; bash'" },
  { "gdbgui",                 "urxvt -e sh -c 'gdbgui -h ; bash'" },
  { "ghidra",                 "urxvt -e sh -c 'ghidra ; bash'" },
  { "ghidra-analyzeHeadless", "urxvt -e sh -c 'ghidra-analyzeHeadless ; bash'" },
  { "ghidra",                 "urxvt -e sh -c 'ghidra ; bash'" },
  { "ghidra-analyzeHeadless", "urxvt -e sh -c 'ghidra-analyzeHeadless ; bash'" },
  { "iaito",                  "urxvt -e sh -c 'iaito ; bash'" },
  { "gen-bout",               "urxvt -e sh -c 'gen-bout ; bash'" },
  { "gen-random-bout",        "urxvt -e sh -c 'gen-random-bout ; bash'" },
  { "kleaver",                "urxvt -e sh -c 'kleaver -h ; bash'" },
  { "klee",                   "urxvt -e sh -c 'klee -h ; bash'" },
  { "klee-stats",             "urxvt -e sh -c 'klee-stats -h ; bash'" },
  { "ktest-tool",             "urxvt -e sh -c 'ktest-tool -h ; bash'" },
  { "lldb",                   "urxvt -e sh -c 'lldb ; bash'" },
  { "lldb-argdumper",         "urxvt -e sh -c 'lldb-argdumper ; bash'" },
  { "lldb-instr",             "urxvt -e sh -c 'lldb-instr ; bash'" },
  { "lldb-server",            "urxvt -e sh -c 'lldb-server ; bash'" },
  { "lldb-vscode",            "urxvt -e sh -c 'lldb-vscode ; bash'" },
  { "lldb",                   "urxvt -e sh -c 'lldb ; bash'" },
  { "lldb-argdumper",         "urxvt -e sh -c 'lldb-argdumper ; bash'" },
  { "lldb-instr",             "urxvt -e sh -c 'lldb-instr ; bash'" },
  { "lldb-server",            "urxvt -e sh -c 'lldb-server ; bash'" },
  { "lldb-vscode",            "urxvt -e sh -c 'lldb-vscode ; bash'" },
  { "malwasm",                "urxvt -e sh -c 'malwasm ; bash'" },
  { "ollydbg",                "urxvt -e sh -c 'ollydbg ; bash'" },
  { "plasma-disasm",          "urxvt -e sh -c 'plasma-disasm -h ; bash'" },
  { "r2",                     "urxvt -e sh -c 'r2 -h ; bash'" },
  { "r2agent",                "urxvt -e sh -c 'r2agent -h ; bash'" },
  { "r2pm",                   "urxvt -e sh -c 'r2pm ; bash'" },
  { "r2r",                    "urxvt -e sh -c 'r2r ; bash'" },
  { "radare2",                "urxvt -e sh -c 'radare2 -h ; bash'" },
  { "radiff2",                "urxvt -e sh -c 'radiff2 -h ; bash'" },
  { "rafind2",                "urxvt -e sh -c 'rafind2 -h ; bash'" },
  { "ragg2",                  "urxvt -e sh -c 'ragg2 -h ; bash'" },
  { "rarun2",                 "urxvt -e sh -c 'rarun2 -h ; bash'" },
  { "rasign2",                "urxvt -e sh -c 'rasign2 ; bash'" },
  { "rasm2",                  "urxvt -e sh -c 'rasm2 -h ; bash'" },
  { "rax2",                   "urxvt -e sh -c 'rax2 ; bash'" },
  { "rvc2",                   "urxvt -e sh -c 'rvc2 ; bash'" },
  { "r2",                     "urxvt -e sh -c 'r2 -h ; bash'" },
  { "r2agent",                "urxvt -e sh -c 'r2agent -h ; bash'" },
  { "r2pm",                   "urxvt -e sh -c 'r2pm ; bash'" },
  { "r2r",                    "urxvt -e sh -c 'r2r ; bash'" },
  { "radare2",                "urxvt -e sh -c 'radare2 -h ; bash'" },
  { "radiff2",                "urxvt -e sh -c 'radiff2 -h ; bash'" },
  { "rafind2",                "urxvt -e sh -c 'rafind2 -h ; bash'" },
  { "ragg2",                  "urxvt -e sh -c 'ragg2 -h ; bash'" },
  { "rarun2",                 "urxvt -e sh -c 'rarun2 -h ; bash'" },
  { "rasign2",                "urxvt -e sh -c 'rasign2 ; bash'" },
  { "rasm2",                  "urxvt -e sh -c 'rasm2 -h ; bash'" },
  { "rax2",                   "urxvt -e sh -c 'rax2 ; bash'" },
  { "rvc2",                   "urxvt -e sh -c 'rvc2 ; bash'" },
  { "rr",                     "urxvt -e sh -c 'rr -h ; bash'" },
  { "saleae-logic",           "urxvt -e sh -c 'saleae-logic ; bash'" },
  { "cygdb",                  "urxvt -e sh -c 'cygdb ; bash'" },
  { "cython",                 "urxvt -e sh -c 'cython ; bash'" },
  { "cythonize",              "urxvt -e sh -c 'cythonize ; bash'" },
  { "py.test",                "urxvt -e sh -c 'py.test ; bash'" },
  { "pytest",                 "urxvt -e sh -c 'pytest ; bash'" },
  { "shellnoob",              "urxvt -e sh -c 'shellnoob -h ; bash'" },
  { "voltron",                "urxvt -e sh -c 'voltron -h ; bash'" },
}

return debuggermenu
