decompilermenu = {
  { "beebug",                                "urxvt -e sh -c 'beebug -h ; bash'" },
  { "cafebabe",                              "urxvt -e sh -c 'cafebabe ; bash'" },
  { "cfr",                                   "urxvt -e sh -c 'cfr --help ; bash'" },
  { "fernflower",                            "urxvt -e sh -c 'fernflower -h ; bash'" },
  { "flasm",                                 "urxvt -e sh -c 'flasm -h ; bash'" },
  { "gadgetinspector",                       "urxvt -e sh -c 'gadgetinspector ; bash'" },
  { "hopper",                                "urxvt -e sh -c 'hopper ; bash'" },
  { "iaito",                                 "urxvt -e sh -c 'iaito ; bash'" },
  { "jadx",                                  "urxvt -e sh -c 'jadx -h ; bash'" },
  { "jadx-gui",                              "urxvt -e sh -c 'jadx-gui ; bash'" },
  { "jadx",                                  "urxvt -e sh -c 'jadx -h ; bash'" },
  { "jadx-gui",                              "urxvt -e sh -c 'jadx-gui ; bash'" },
  { "jadx",                                  "urxvt -e sh -c 'jadx -h ; bash'" },
  { "jadx-gui",                              "urxvt -e sh -c 'jadx-gui ; bash'" },
  { "jadx",                                  "urxvt -e sh -c 'jadx -h ; bash'" },
  { "jadx-gui",                              "urxvt -e sh -c 'jadx-gui ; bash'" },
  { "jd-cli",                                "urxvt -e sh -c 'jd-cli -h ; bash'" },
  { "jd-gui",                                "urxvt -e sh -c 'jd-gui ; bash'" },
  { "jpexs-decompiler",                      "urxvt -e sh -c 'jpexs-decompiler ; bash'" },
  { "luyten",                                "urxvt -e sh -c 'luyten ; bash'" },
  { "pcode2code",                            "urxvt -e sh -c 'pcode2code -h ; bash'" },
  { "procyon",                               "urxvt -e sh -c 'procyon ; bash'" },
  { "pydisassemble",                         "urxvt -e sh -c 'pydisassemble ; bash'" },
  { "r2",                                    "urxvt -e sh -c 'r2 -h ; bash'" },
  { "r2agent",                               "urxvt -e sh -c 'r2agent -h ; bash'" },
  { "r2pm",                                  "urxvt -e sh -c 'r2pm ; bash'" },
  { "r2r",                                   "urxvt -e sh -c 'r2r ; bash'" },
  { "radare2",                               "urxvt -e sh -c 'radare2 -h ; bash'" },
  { "radiff2",                               "urxvt -e sh -c 'radiff2 -h ; bash'" },
  { "rafind2",                               "urxvt -e sh -c 'rafind2 -h ; bash'" },
  { "ragg2",                                 "urxvt -e sh -c 'ragg2 -h ; bash'" },
  { "rarun2",                                "urxvt -e sh -c 'rarun2 -h ; bash'" },
  { "rasign2",                               "urxvt -e sh -c 'rasign2 ; bash'" },
  { "rasm2",                                 "urxvt -e sh -c 'rasm2 -h ; bash'" },
  { "rax2",                                  "urxvt -e sh -c 'rax2 ; bash'" },
  { "rvc2",                                  "urxvt -e sh -c 'rvc2 ; bash'" },
  { "r2",                                    "urxvt -e sh -c 'r2 -h ; bash'" },
  { "r2agent",                               "urxvt -e sh -c 'r2agent -h ; bash'" },
  { "r2pm",                                  "urxvt -e sh -c 'r2pm ; bash'" },
  { "r2r",                                   "urxvt -e sh -c 'r2r ; bash'" },
  { "radare2",                               "urxvt -e sh -c 'radare2 -h ; bash'" },
  { "radiff2",                               "urxvt -e sh -c 'radiff2 -h ; bash'" },
  { "rafind2",                               "urxvt -e sh -c 'rafind2 -h ; bash'" },
  { "ragg2",                                 "urxvt -e sh -c 'ragg2 -h ; bash'" },
  { "rarun2",                                "urxvt -e sh -c 'rarun2 -h ; bash'" },
  { "rasign2",                               "urxvt -e sh -c 'rasign2 ; bash'" },
  { "rasm2",                                 "urxvt -e sh -c 'rasm2 -h ; bash'" },
  { "rax2",                                  "urxvt -e sh -c 'rax2 ; bash'" },
  { "rvc2",                                  "urxvt -e sh -c 'rvc2 ; bash'" },
  { "recaf",                                 "urxvt -e sh -c 'recaf ; bash'" },
  { "recstudio",                             "urxvt -e sh -c 'recstudio ; bash'" },
  { "retdec-ar-extractor",                   "urxvt -e sh -c 'retdec-ar-extractor -h ; bash'" },
  { "retdec-archive-decompiler",             "urxvt -e sh -c 'retdec-archive-decompiler -h ; bash'" },
  { "retdec-color-c",                        "urxvt -e sh -c 'retdec-color-c -h ; bash'" },
  { "retdec-decompiler",                     "urxvt -e sh -c 'retdec-decompiler -h ; bash'" },
  { "retdec-fileinfo",                       "urxvt -e sh -c 'retdec-fileinfo -h ; bash'" },
  { "retdec-getsig",                         "urxvt -e sh -c 'retdec-getsig -h ; bash'" },
  { "retdec-idr2pat",                        "urxvt -e sh -c 'retdec-idr2pat -h ; bash'" },
  { "retdec-macho-extractor",                "urxvt -e sh -c 'retdec-macho-extractor -h ; bash'" },
  { "retdec-pat2yara",                       "urxvt -e sh -c 'retdec-pat2yara -h ; bash'" },
  { "retdec-signature-from-library-creator", "urxvt -e sh -c 'retdec-signature-from-library-creator -h ; bash'" },
  { "retdec-stacofin",                       "urxvt -e sh -c 'retdec-stacofin -h ; bash'" },
  { "retdec-unpacker",                       "urxvt -e sh -c 'retdec-unpacker -h ; bash'" },
  { "retdec-utils",                          "urxvt -e sh -c 'retdec-utils -h ; bash'" },
  { "retdec-yarac",                          "urxvt -e sh -c 'retdec-yarac ; bash'" },
}

return decompilermenu
